import { BeginnerLesson, ConjugationRow, VocabularyItem } from './lessonTypes'

const requiredSections: BeginnerLesson['completion_criteria']['required_sections'] = ['dialogue', 'grammar', 'vocabulary', 'exercises']

const criteria = {
  min_exercises_correct: 6,
  required_sections: requiredSections,
}

const skills: BeginnerLesson['cefr_skills'] = ['listening', 'speaking', 'reading', 'writing']

const v = (
  word: string,
  translation: string,
  pronunciation: string,
  example_sentence: string,
  example_translation: string,
  category: string,
  gender?: VocabularyItem['gender'],
): VocabularyItem => ({
  word,
  translation,
  pronunciation,
  example_sentence,
  example_translation,
  category,
  ...(gender ? { gender } : {}),
})

const row = (pronoun: string, form: string, pronunciation: string): ConjugationRow => ({
  pronoun,
  form,
  pronunciation,
})

const etre = [
  row('je', 'suis', 'swee'),
  row('tu', 'es', 'ay'),
  row('il/elle/on', 'est', 'ay'),
  row('nous', 'sommes', 'sum'),
  row('vous', 'êtes', 'zet'),
  row('ils/elles', 'sont', 'sohn'),
]

const avoir = [
  row("j'", 'ai', 'ay'),
  row('tu', 'as', 'ah'),
  row('il/elle/on', 'a', 'ah'),
  row('nous', 'avons', 'ah-VOHN'),
  row('vous', 'avez', 'ah-VAY'),
  row('ils/elles', 'ont', 'ohn'),
]

const parler = [
  row('je', 'parle', 'parl'),
  row('tu', 'parles', 'parl'),
  row('il/elle/on', 'parle', 'parl'),
  row('nous', 'parlons', 'par-LOHN'),
  row('vous', 'parlez', 'par-LAY'),
  row('ils/elles', 'parlent', 'parl'),
]

const makeBase = (
  order: number,
  title: string,
  title_fr: string,
  subtitle: string,
  difficulty: BeginnerLesson['difficulty'],
  tags: string[],
  partial: Omit<BeginnerLesson, 'id' | 'title' | 'title_fr' | 'subtitle' | 'level' | 'cefr_skills' | 'order' | 'estimated_time' | 'tags' | 'difficulty' | 'is_free' | 'completion_criteria'>,
): BeginnerLesson => ({
  id: `beginner-${order}`,
  title,
  title_fr,
  subtitle,
  level: 'A1',
  cefr_skills: skills,
  order,
  estimated_time: order <= 2 ? 30 : order <= 8 ? 40 : 45,
  tags,
  difficulty,
  is_free: order <= 6,
  completion_criteria: criteria,
  ...partial,
})

export const beginnerLessons: BeginnerLesson[] = [
  makeBase(1, 'First Contacts', 'Premiers Contacts', 'Use être, polite greetings, and tu/vous in a short café encounter.', 1, ['être', 'greetings', 'tu-vous'], {
    learning_objectives: [
      'Use formal greetings in a public setting',
      'Conjugate être in the present tense',
      'Choose vous for a stranger and tu for a familiar person',
      'Say who you are and where you are from',
    ],
    dialogue: {
      title: 'Une place au café',
      context: 'Two strangers meet briefly at a Parisian café and keep the exchange formal.',
      exchanges: [
        { speaker: 'Claire', french: 'Bonjour, monsieur.', english: 'Hello, sir.', pronunciation: 'bon-ZHOOR muh-SYUH' },
        { speaker: 'Marc', french: 'Bonjour, madame.', english: 'Hello, ma’am.', pronunciation: 'bon-ZHOOR ma-DAM' },
        { speaker: 'Claire', french: 'Merci. Vous êtes ici?', english: 'Thank you. Are you here?', pronunciation: 'mer-SEE voo zet zee-SEE' },
        { speaker: 'Marc', french: 'De rien. Vous êtes française?', english: 'You’re welcome. Are you French?', pronunciation: 'duh ree-AHN voo zet frahn-SEZ' },
        { speaker: 'Claire', french: 'Oui, je suis française. Et vous?', english: 'Yes, I am French. And you?', pronunciation: 'wee zhuh swee frahn-SEZ ay voo' },
        { speaker: 'Marc', french: 'Moi, je suis canadien. Je suis ici.', english: 'Me, I am Canadian. I am here.', pronunciation: 'mwah zhuh swee ka-na-DYEN zhuh swee zee-SEE' },
        { speaker: 'Claire', french: 'Très bien. Au revoir, monsieur.', english: 'Very good. Goodbye, sir.', pronunciation: 'tray byahn oh ruh-VWAHR muh-SYUH' },
        { speaker: 'Marc', french: 'Au revoir, madame.', english: 'Goodbye, ma’am.', pronunciation: 'oh ruh-VWAHR ma-DAM' },
      ],
      cultural_notes: [
        'In France, bonjour is expected before asking a question in a café, shop, or office.',
        'Vous is the normal choice with adult strangers; switching to tu usually happens only by invitation or shared context.',
        'Madame and monsieur are still common in service encounters, though many younger speakers avoid overly formal titles among peers.',
      ],
      vocabulary_highlights: ['bonjour', 'merci', 'vous', 'je suis'],
    },
    grammar: {
      topic: 'Être and Tu/Vous',
      explanation: 'Être means “to be,” but in French it is not just a vocabulary word. It is the verb you need for identity, nationality, location, and simple descriptions: je suis étudiant, elle est française, nous sommes ici.\n\nThe forms are irregular, so do not try to build them from a rule yet. Memorize each subject with its verb form. Also notice that French has two “you” forms: tu for one familiar person, and vous for a stranger, a formal situation, or more than one person.',
      examples: [
        { french: 'Je suis française.', english: 'I am French.', pronunciation: 'zhuh swee frahn-SEZ', highlight: 'suis' },
        { french: 'Vous êtes ici.', english: 'You are here.', pronunciation: 'voo zet zee-SEE', highlight: 'êtes' },
        { french: 'Ils sont canadiens.', english: 'They are Canadian.', pronunciation: 'eel sohn ka-na-DYEN', highlight: 'sont' },
      ],
      patterns: ['je suis', 'tu es', 'il/elle est', 'nous sommes', 'vous êtes', 'ils/elles sont'],
      conjugation_tables: [{ verb: 'être', rows: etre }],
      tip: "In French, you don't say “I am well” with être. Learn fixed phrases like Ça va and Je vais bien separately; they do not follow this pattern.",
    },
    vocabulary: [
      v('bonjour', 'hello / good day', 'bon-ZHOOR', 'Bonjour, madame.', 'Hello, ma’am.', 'greetings'),
      v('bonsoir', 'good evening', 'bon-SWAHR', 'Bonsoir, monsieur.', 'Good evening, sir.', 'greetings'),
      v('salut', 'hi / bye', 'sa-LOO', 'Salut, tu es ici.', 'Hi, you are here.', 'greetings'),
      v('au revoir', 'goodbye', 'oh ruh-VWAHR', 'Au revoir, madame.', 'Goodbye, ma’am.', 'farewells'),
      v('merci', 'thank you', 'mer-SEE', 'Merci, monsieur.', 'Thank you, sir.', 'politeness'),
      v("s'il vous plaît", 'please', 'seel voo PLEH', "S'il vous plaît, monsieur.", 'Please, sir.', 'politeness'),
      v('de rien', "you're welcome", 'duh ree-AHN', 'De rien, madame.', 'You’re welcome, ma’am.', 'politeness'),
      v('excusez-moi', 'excuse me', 'ex-koo-zay MWAH', 'Excusez-moi, monsieur.', 'Excuse me, sir.', 'politeness'),
      v('pardon', 'sorry / pardon', 'par-DOHN', 'Pardon, madame.', 'Sorry, ma’am.', 'politeness'),
      v('ici', 'here', 'ee-SEE', 'Je suis ici.', 'I am here.', 'place'),
      v('bien', 'well / good', 'byahn', 'Très bien.', 'Very good.', 'basic'),
      v('très bien', 'very well', 'tray byahn', 'Je suis très bien.', 'I am very well.', 'basic'),
      v('français', 'French', 'frahn-SAY', 'Vous êtes français.', 'You are French.', 'nationality'),
      v('française', 'French', 'frahn-SEZ', 'Je suis française.', 'I am French.', 'nationality'),
      v('canadien', 'Canadian', 'ka-na-DYEN', 'Je suis canadien.', 'I am Canadian.', 'nationality'),
      v('belge', 'Belgian', 'belzh', 'Elle est belge.', 'She is Belgian.', 'nationality'),
    ],
    exercises: [
      { id: 'l1-e1', type: 'conjugation', question: 'Conjugate être in the present tense.', verb: 'être', correct_answer: etre, explanation: 'Être is irregular, so each form must be memorized.' },
      { id: 'l1-e2', type: 'multiple_choice', question: 'You meet an adult stranger. Which “you” is safest?', options: ['tu', 'vous', 'toi'], correct_answer: 'vous', explanation: 'Use vous with adult strangers.' },
      { id: 'l1-e3', type: 'fill_blank', question: 'Je ___ française.', correct_answer: 'suis', explanation: 'Je takes suis.' },
      { id: 'l1-e4', type: 'fill_blank', question: 'Vous ___ ici.', correct_answer: 'êtes', explanation: 'Vous takes êtes.' },
      { id: 'l1-e5', type: 'matching', question: 'Match each greeting or farewell.', pairs: [{ french: 'bonjour', english: 'hello / good day' }, { french: 'bonsoir', english: 'good evening' }, { french: 'au revoir', english: 'goodbye' }, { french: 'merci', english: 'thank you' }], explanation: 'These fixed phrases carry the social opening of many French interactions.' },
      { id: 'l1-e6', type: 'translation', question: 'EN→FR: I am Canadian.', direction: 'en_to_fr', correct_answer: ['Je suis canadien.', 'Je suis canadienne.'], explanation: 'Use je suis plus nationality.' },
      { id: 'l1-e7', type: 'translation', question: 'EN→FR: You are here.', direction: 'en_to_fr', correct_answer: 'Vous êtes ici.', explanation: 'Use vous êtes for formal “you are.”' },
      { id: 'l1-e8', type: 'speaking_prompt', question: 'Say hello formally and say who you are.', model_answer: 'Bonjour. Je suis Claire.', translation: 'Hello. I am Claire.', tip: 'Keep bonjour clear before your introduction.' },
    ],
  }),

  makeBase(2, 'Introducing Yourself', 'Se Présenter', 'Use avoir, ages, numbers 1-20, professions, and nationality complements.', 1, ['avoir', 'numbers', 'age'], {
    learning_objectives: [
      'Conjugate avoir in the present tense',
      'Say your age with j’ai X ans',
      'Recognize numbers from 1 to 20',
      'Use basic professions and nationalities after être',
    ],
    prerequisite_lessons: ['beginner-1'],
    dialogue: {
      title: 'Dans le TGV',
      context: 'Two travellers share a train compartment from Paris to Lyon and introduce themselves formally.',
      exchanges: [
        { speaker: 'Nadia', french: 'Bonjour, monsieur. Vous êtes de Lyon?', english: 'Hello, sir. Are you from Lyon?', pronunciation: 'bon-ZHOOR muh-SYUH voo zet duh lee-OHN' },
        { speaker: 'Paul', french: 'Bonjour. Oui, je suis lyonnais.', english: 'Hello. Yes, I am from Lyon.', pronunciation: 'bon-ZHOOR wee zhuh swee lee-oh-NEH' },
        { speaker: 'Nadia', french: 'Moi, je suis de Paris.', english: 'Me, I am from Paris.', pronunciation: 'mwah zhuh swee duh pa-REE' },
        { speaker: 'Paul', french: 'Vous êtes étudiante?', english: 'Are you a student?', pronunciation: 'voo zet ay-too-DYAHNT' },
        { speaker: 'Nadia', french: 'Oui, je suis étudiante. J’ai vingt ans.', english: 'Yes, I am a student. I am twenty.', pronunciation: 'wee zhuh swee ay-too-DYAHNT zhay van tahn' },
        { speaker: 'Paul', french: 'Moi, je suis ingénieur. J’ai trente ans.', english: 'Me, I am an engineer. I am thirty.', pronunciation: 'mwah zhuh swee an-zhay-NYUHR zhay trahnt ahn' },
        { speaker: 'Nadia', french: 'Vous avez chaud?', english: 'Are you hot?', pronunciation: 'voo zah-VAY shoh' },
        { speaker: 'Paul', french: 'Non, j’ai froid.', english: 'No, I am cold.', pronunciation: 'nohn zhay frwah' },
      ],
      cultural_notes: [
        'TGV train tickets identify carriage and seat numbers, so polite negotiation happens mostly when luggage or seats are confusing.',
        'French uses “I have X years” for age; this is not optional in standard French.',
        'Professions after être often appear without an article: Je suis ingénieur, not je suis un ingénieur in basic identification.',
      ],
    },
    grammar: {
      topic: 'Avoir, Age, and Numbers 1-20',
      explanation: 'Avoir means “to have.” French uses it for possession, but also for several ideas where English uses “to be.” The most important beginner pattern is age: j’ai vingt ans, literally “I have twenty years.”\n\nAvoir also appears in fixed everyday expressions such as j’ai faim, j’ai soif, j’ai chaud, and j’ai froid. Learn these as French patterns, not as word-for-word translations from English.',
      examples: [
        { french: 'J’ai vingt ans.', english: 'I am twenty years old.', pronunciation: 'zhay van tahn', highlight: 'J’ai' },
        { french: 'Vous avez froid.', english: 'You are cold.', pronunciation: 'voo zah-VAY frwah', highlight: 'avez' },
        { french: 'Elle a raison.', english: 'She is right.', pronunciation: 'el ah reh-ZOHN', highlight: 'a' },
      ],
      patterns: ['j’ai', 'tu as', 'il/elle a', 'nous avons', 'vous avez', 'ils/elles ont'],
      conjugation_tables: [{ verb: 'avoir', rows: avoir }],
      tip: 'Avoir means “to have” but French uses it where English uses “to be” for age and sensations. Never say je suis 25 ans; always say j’ai 25 ans.',
    },
    vocabulary: [
      v('un', 'one', 'uhn', 'J’ai un an.', 'I am one year old.', 'numbers'),
      v('deux', 'two', 'duh', 'J’ai deux ans.', 'I am two years old.', 'numbers'),
      v('trois', 'three', 'trwah', 'J’ai trois ans.', 'I am three years old.', 'numbers'),
      v('quatre', 'four', 'katr', 'J’ai quatre ans.', 'I am four.', 'numbers'),
      v('cinq', 'five', 'sank', 'J’ai cinq ans.', 'I am five years old.', 'numbers'),
      v('dix', 'ten', 'dees', 'J’ai dix ans.', 'I am ten.', 'numbers'),
      v('quinze', 'fifteen', 'kanz', 'J’ai quinze ans.', 'I am fifteen.', 'numbers'),
      v('vingt', 'twenty', 'van', 'J’ai vingt ans.', 'I am twenty.', 'numbers'),
      v('faim', 'hunger', 'fam', 'J’ai faim.', 'I am hungry.', 'avoir expression'),
      v('soif', 'thirst', 'swaf', 'J’ai soif.', 'I am thirsty.', 'avoir expression'),
      v('chaud', 'hot', 'shoh', 'J’ai chaud.', 'I am hot.', 'avoir expression'),
      v('froid', 'cold', 'frwah', 'J’ai froid.', 'I am cold.', 'avoir expression'),
      v('raison', 'right', 'reh-ZOHN', 'Vous avez raison.', 'You are right.', 'avoir expression'),
      v('étudiant', 'student', 'ay-too-DYAHN', 'Je suis étudiant.', 'I am a student.', 'profession'),
      v('professeur', 'teacher', 'pro-feh-SUHR', 'Elle est professeur.', 'She is a teacher.', 'profession'),
      v('ingénieur', 'engineer', 'an-zhay-NYUHR', 'Il est ingénieur.', 'He is an engineer.', 'profession'),
      v('médecin', 'doctor', 'mayd-SAN', 'Vous êtes médecin.', 'You are a doctor.', 'profession'),
      v('lyonnais', 'from Lyon', 'lee-oh-NEH', 'Je suis lyonnais.', 'I am from Lyon.', 'nationality'),
    ],
    exercises: [
      { id: 'l2-e1', type: 'conjugation', question: 'Conjugate avoir in the present tense.', verb: 'avoir', correct_answer: avoir, explanation: 'Avoir is irregular and required for age.' },
      { id: 'l2-e2', type: 'matching', question: 'Match numbers to digits.', pairs: [{ french: 'un', english: '1' }, { french: 'deux', english: '2' }, { french: 'quinze', english: '15' }, { french: 'vingt', english: '20' }], explanation: 'Numbers 1-20 are the base for age.' },
      { id: 'l2-e3', type: 'fill_blank', question: 'J’___ vingt ans.', correct_answer: 'ai', explanation: 'Age uses avoir: j’ai vingt ans.' },
      { id: 'l2-e4', type: 'multiple_choice', question: 'Which sentence is correct?', options: ['Je suis vingt ans.', 'J’ai vingt ans.', 'Je est vingt ans.'], correct_answer: 'J’ai vingt ans.', explanation: 'French uses avoir for age.' },
      { id: 'l2-e5', type: 'fill_blank', question: 'Vous ___ froid.', correct_answer: 'avez', explanation: 'Vous takes avez.' },
      { id: 'l2-e6', type: 'multiple_choice', question: 'Which profession phrase is standard?', options: ['Je suis professeur.', 'Je suis un professeur toujours.', 'J’ai professeur.'], correct_answer: 'Je suis professeur.', explanation: 'Basic profession complements usually use être without an article.' },
      { id: 'l2-e7', type: 'translation', question: 'EN→FR: I am thirsty.', direction: 'en_to_fr', correct_answer: 'J’ai soif.', explanation: 'Thirst uses avoir in French.' },
      { id: 'l2-e8', type: 'translation', question: 'EN→FR: You are a student.', direction: 'en_to_fr', correct_answer: ['Vous êtes étudiant.', 'Vous êtes étudiante.'], explanation: 'Use être for profession or student identity.' },
    ],
  }),

  makeBase(3, 'Regular -er Verbs', 'Les Verbes en -er', 'Conjugate core regular verbs to talk about study, work, hobbies, and home.', 2, ['-er verbs', 'infinitive', 'campus'], {
    learning_objectives: [
      'Recognize the infinitive form of regular -er verbs',
      'Conjugate parler and habiter for all six pronouns',
      'Describe where you live and what you study',
      'Use common adverbs such as souvent and maintenant',
    ],
    prerequisite_lessons: ['beginner-2'],
    dialogue: {
      title: 'Sur le campus',
      context: 'Two students meet on a university campus and move from formal vous to friendly tu.',
      exchanges: [
        { speaker: 'Emma', french: 'Bonjour, vous êtes étudiante ici?', english: 'Hello, are you a student here?', pronunciation: 'bon-ZHOOR voo zet ay-too-DYAHNT ee-SEE' },
        { speaker: 'Lucas', french: 'Oui, je suis étudiant. J’étudie ici.', english: 'Yes, I am a student. I study here.', pronunciation: 'wee zhuh swee ay-too-DYAHN zhay-too-DEE ee-SEE' },
        { speaker: 'Emma', french: 'Moi aussi. J’habite à Paris.', english: 'Me too. I live in Paris.', pronunciation: 'mwah oh-SEE zha-BEET ah pa-REE' },
        { speaker: 'Lucas', french: 'Moi, j’habite ici. Tu parles anglais?', english: 'Me, I live here. Do you speak English?', pronunciation: 'mwah zha-BEET ee-SEE too parl ahn-GLEH' },
        { speaker: 'Emma', french: 'Oui, je parle anglais et français.', english: 'Yes, I speak English and French.', pronunciation: 'wee zhuh parl ahn-GLEH ay frahn-SAY' },
        { speaker: 'Lucas', french: 'Nous travaillons beaucoup maintenant.', english: 'We work a lot now.', pronunciation: 'noo tra-vah-YOHN bo-KOO man-tuh-NAHN' },
        { speaker: 'Emma', french: 'Oui, et nous écoutons souvent Emma.', english: 'Yes, and we often listen to Emma.', pronunciation: 'wee ay noo zay-koo-TOHN soo-VAHN em-MAH' },
        { speaker: 'Lucas', french: 'Après, tu marches avec moi?', english: 'Afterward, do you walk with me?', pronunciation: 'ah-PREH too marsh ah-VEK mwah' },
      ],
      cultural_notes: [
        'Students of similar age often switch to tu quickly once they recognize a shared peer context.',
        'French university life is usually less campus-residential than in North America; many students commute from apartments or family homes.',
        'À plus a city is introduced as a fixed location pattern here: J’habite à Paris.',
      ],
    },
    grammar: {
      topic: 'Regular -er Verbs',
      explanation: 'Regular -er verbs are the largest verb family in French. Start with the infinitive, remove -er, and attach the present-tense ending for the subject: je parle, nous parlons, vous parlez.\n\nIn writing the endings differ, but in speech several forms sound the same: parle, parles, and parlent are pronounced alike. That means the subject pronoun does a lot of work, so keep it clear.',
      examples: [
        { french: 'Je parle français.', english: 'I speak French.', pronunciation: 'zhuh parl frahn-SAY', highlight: 'parle' },
        { french: 'Nous habitons ici.', english: 'We live here.', pronunciation: 'noo zah-bee-TOHN ee-SEE', highlight: 'habitons' },
        { french: 'Vous travaillez beaucoup.', english: 'You work a lot.', pronunciation: 'voo tra-vah-YAY bo-KOO', highlight: 'travaillez' },
      ],
      patterns: ['infinitive: parler', 'stem: parl-', 'je/tu/il forms sound alike', 'nous adds -ons', 'vous adds -ez', 'ils/elles add silent -ent'],
      conjugation_tables: [{ verb: 'parler', rows: parler }],
      tip: "The -e, -es, and -e forms all sound identical. In speech, you already sound natural if you know the stem.",
    },
    vocabulary: [
      v('parler', 'to speak', 'par-LAY', 'Je parle français.', 'I speak French.', 'verbs'),
      v('habiter', 'to live', 'ah-bee-TAY', 'J’habite à Paris.', 'I live in Paris.', 'verbs'),
      v('travailler', 'to work', 'tra-vah-YAY', 'Nous travaillons beaucoup.', 'We work a lot.', 'verbs'),
      v('aimer', 'to like / love', 'eh-MAY', 'Tu aimes Paris.', 'You like Paris.', 'verbs'),
      v('écouter', 'to listen', 'ay-koo-TAY', 'Nous écoutons Emma.', 'We listen to Emma.', 'verbs'),
      v('regarder', 'to watch / look at', 'ruh-gar-DAY', 'Tu regardes Marie.', 'You look at Marie.', 'verbs'),
      v('étudier', 'to study', 'ay-too-DYAY', 'J’étudie ici.', 'I study here.', 'verbs'),
      v('marcher', 'to walk', 'mar-SHAY', 'Elle marche ici.', 'She walks here.', 'verbs'),
      v('chanter', 'to sing', 'shahn-TAY', 'Ils chantent souvent.', 'They often sing.', 'verbs'),
      v('danser', 'to dance', 'dahn-SAY', 'Elles dansent beaucoup.', 'They dance a lot.', 'verbs'),
      v('jouer', 'to play', 'zhoo-AY', 'Nous jouons ici.', 'We play here.', 'verbs'),
      v('beaucoup', 'a lot', 'bo-KOO', 'Nous travaillons beaucoup.', 'We work a lot.', 'adverbs'),
      v('souvent', 'often', 'soo-VAHN', 'Tu écoutes souvent.', 'You often listen.', 'adverbs'),
      v('toujours', 'always', 'too-ZHOOR', 'Je parle toujours.', 'I always speak.', 'adverbs'),
      v('jamais', 'never', 'zha-MEH', 'Je chante jamais.', 'I never sing.', 'adverbs'),
      v('aussi', 'also / too', 'oh-SEE', 'Moi aussi.', 'Me too.', 'adverbs'),
      v('maintenant', 'now', 'man-tuh-NAHN', 'Nous travaillons maintenant.', 'We work now.', 'time'),
      v('avec', 'with', 'ah-VEK', 'Je travaille avec Emma.', 'I work with Emma.', 'connectors'),
    ],
    exercises: [
      { id: 'l3-e1', type: 'conjugation', question: 'Conjugate parler for all six pronouns.', verb: 'parler', correct_answer: parler, explanation: 'Parler uses the regular -er endings.' },
      { id: 'l3-e2', type: 'conjugation', question: 'Conjugate habiter for all six pronouns.', verb: 'habiter', correct_answer: [row('je', 'habite', 'ah-BEET'), row('tu', 'habites', 'ah-BEET'), row('il/elle/on', 'habite', 'ah-BEET'), row('nous', 'habitons', 'ah-bee-TOHN'), row('vous', 'habitez', 'ah-bee-TAY'), row('ils/elles', 'habitent', 'ah-BEET')], explanation: 'Habiter follows the same endings as parler.' },
      { id: 'l3-e3', type: 'matching', question: 'Match infinitives to meanings.', pairs: [{ french: 'parler', english: 'to speak' }, { french: 'habiter', english: 'to live' }, { french: 'travailler', english: 'to work' }, { french: 'écouter', english: 'to listen' }], explanation: 'The infinitive is the dictionary form.' },
      { id: 'l3-e4', type: 'multiple_choice', question: 'Choose the correct form: nous ___ français.', options: ['parle', 'parlez', 'parlons'], correct_answer: 'parlons', explanation: 'Nous takes -ons.' },
      { id: 'l3-e5', type: 'fill_blank', question: 'Tu ___ à Paris.', correct_answer: 'habites', explanation: 'Tu takes -es in writing.' },
      { id: 'l3-e6', type: 'translation', question: 'EN→FR: I study French.', direction: 'en_to_fr', correct_answer: 'J’étudie le français.', explanation: 'Étudier becomes j’étudie.' },
      { id: 'l3-e7', type: 'translation', question: 'EN→FR: We work a lot.', direction: 'en_to_fr', correct_answer: 'Nous travaillons beaucoup.', explanation: 'Nous takes travaillons.' },
      { id: 'l3-e8', type: 'speaking_prompt', question: 'Introduce yourself with three -er verbs.', model_answer: 'Je parle français, j’habite à Paris et j’étudie beaucoup.', translation: 'I speak French, I live in Paris, and I study a lot.', tip: 'Moi and toi are emphatic pronouns you can use now; you will study the full set later.' },
    ],
  }),

  makeBase(4, 'Articles and Gender', 'Les Articles et le Genre', 'Use le, la, l’, les, un, une, des, noun gender, plurals, and article contractions.', 2, ['articles', 'gender', 'market'], {
    learning_objectives: [
      'Choose definite and indefinite articles',
      'Identify common masculine and feminine noun patterns',
      'Make regular nouns plural',
      'Recognize au, du, aux, and des as contractions',
    ],
    prerequisite_lessons: ['beginner-3'],
    dialogue: {
      title: 'Au marché',
      context: 'Two friends at an outdoor market choose items using indefinite articles only.',
      exchanges: [
        { speaker: 'Sofia', french: 'Le marché est grand.', english: 'The market is big.', pronunciation: 'luh mar-SHAY ay grahn' },
        { speaker: 'Hugo', french: 'Oui, il est très animé.', english: 'Yes, it is very lively.', pronunciation: 'wee eel ay tray ah-nee-MAY' },
        { speaker: 'Sofia', french: 'J’achète une baguette et un fromage.', english: 'I am buying a baguette and a cheese.', pronunciation: 'zah-SHET oon ba-GET ay uhn fro-MAZH' },
        { speaker: 'Hugo', french: 'Moi, j’achète des légumes.', english: 'Me, I am buying vegetables.', pronunciation: 'mwah zah-SHET day lay-GOOM' },
        { speaker: 'Sofia', french: 'La fromagerie est là.', english: 'The cheese shop is there.', pronunciation: 'lah fro-mah-zhuh-REE ay lah' },
        { speaker: 'Hugo', french: 'Et la boulangerie est ici.', english: 'And the bakery is here.', pronunciation: 'ay lah boo-lahn-zhuh-REE ay ee-SEE' },
        { speaker: 'Sofia', french: 'Un sac est utile.', english: 'A bag is useful.', pronunciation: 'uhn sak ay oo-TEEL' },
        { speaker: 'Hugo', french: 'Oui, les sacs sont ici.', english: 'Yes, the bags are here.', pronunciation: 'wee lay sak sohn ee-SEE' },
      ],
      cultural_notes: [
        'Outdoor markets in French cities usually happen on set mornings rather than all day every day.',
        'Many French food shops are specialized: boulangerie for bread, fromagerie for cheese, boucherie for meat.',
        'Learning nouns with articles is practical because gender affects adjectives, possessives, and later pronouns.',
      ],
    },
    grammar: {
      topic: 'Definite and Indefinite Articles',
      explanation: 'Every French noun is grammatically masculine or feminine. This is a property of the word, not the real-world object. Learn nouns with an article from the beginning: le marché, la table, l’école.\n\nDefinite articles point to a known or general noun: le, la, l’, les. Indefinite articles introduce one item or an unspecified plural amount: un, une, des. These article choices matter because they control later adjective and possessive forms.',
      examples: [
        { french: 'le marché', english: 'the market', pronunciation: 'luh mar-SHAY', highlight: 'le' },
        { french: 'une baguette', english: 'a baguette', pronunciation: 'oon ba-GET', highlight: 'une' },
        { french: 'des légumes', english: 'some vegetables', pronunciation: 'day lay-GOOM', highlight: 'des' },
      ],
      patterns: ['le masculine singular', 'la feminine singular', "l’ before vowel or silent h", 'les plural', 'un masculine / une feminine', 'plural usually adds -s'],
      tip: 'You cannot always predict gender from endings. Learn every noun with its article: le pain, la maison.',
    },
    vocabulary: [
      v('le marché', 'market', 'luh mar-SHAY', 'Le marché est grand.', 'The market is big.', 'market', 'masculine'),
      v('la boulangerie', 'bakery', 'lah boo-lahn-zhuh-REE', 'La boulangerie est ici.', 'The bakery is here.', 'shops', 'feminine'),
      v('la boucherie', 'butcher shop', 'lah boosh-REE', 'La boucherie est petite.', 'The butcher shop is small.', 'shops', 'feminine'),
      v('la fromagerie', 'cheese shop', 'lah fro-mah-zhuh-REE', 'La fromagerie est là.', 'The cheese shop is there.', 'shops', 'feminine'),
      v("l'épicerie", 'grocery shop', 'lay-pees-REE', "L'épicerie est utile.", 'The grocery shop is useful.', 'shops', 'feminine'),
      v('le pain', 'bread', 'luh pan', 'Un pain est ici.', 'A loaf is here.', 'food', 'masculine'),
      v('la baguette', 'baguette', 'lah ba-GET', 'Une baguette est petite.', 'A baguette is small.', 'food', 'feminine'),
      v('le fromage', 'cheese', 'luh fro-MAZH', 'Un fromage est bon.', 'A cheese is good.', 'food', 'masculine'),
      v('la viande', 'meat', 'lah vee-AHND', 'Une viande est chère.', 'A meat is expensive.', 'food', 'feminine'),
      v('le légume', 'vegetable', 'luh lay-GOOM', 'Des légumes sont ici.', 'Vegetables are here.', 'food', 'masculine'),
      v('le fruit', 'fruit', 'luh frwee', 'Un fruit est bon.', 'A fruit is good.', 'food', 'masculine'),
      v('le poisson', 'fish', 'luh pwah-SOHN', 'Un poisson est là.', 'A fish is there.', 'food', 'masculine'),
      v('le livre', 'book', 'luh LEE-vruh', 'Le livre est utile.', 'The book is useful.', 'objects', 'masculine'),
      v('le stylo', 'pen', 'luh stee-LOH', 'Un stylo est ici.', 'A pen is here.', 'objects', 'masculine'),
      v('le sac', 'bag', 'luh sak', 'Le sac est grand.', 'The bag is big.', 'objects', 'masculine'),
      v('la table', 'table', 'lah TAHBL', 'La table est libre.', 'The table is free.', 'objects', 'feminine'),
      v('la chaise', 'chair', 'lah shez', 'Une chaise est libre.', 'A chair is free.', 'objects', 'feminine'),
      v('la fenêtre', 'window', 'lah fuh-NETR', 'La fenêtre est grande.', 'The window is big.', 'objects', 'feminine'),
      v('la maison', 'house', 'lah meh-ZOHN', 'La maison est grande.', 'The house is big.', 'places', 'feminine'),
      v("l'école", 'school', 'lay-KOL', "L'école est ici.", 'The school is here.', 'places', 'feminine'),
    ],
    exercises: [
      { id: 'l4-e1', type: 'gender_sort', question: 'Sort these nouns by gender.', items: [{ word: 'marché', gender: 'masculine', article: 'le' }, { word: 'boulangerie', gender: 'feminine', article: 'la' }, { word: 'fromage', gender: 'masculine', article: 'le' }, { word: 'table', gender: 'feminine', article: 'la' }, { word: 'sac', gender: 'masculine', article: 'le' }, { word: 'maison', gender: 'feminine', article: 'la' }], explanation: 'Gender must be learned with the noun.' },
      { id: 'l4-e2', type: 'fill_blank', question: '___ marché est grand.', correct_answer: 'Le', explanation: 'Marché is masculine singular.' },
      { id: 'l4-e3', type: 'fill_blank', question: 'J’achète ___ baguette.', correct_answer: 'une', explanation: 'Baguette is feminine singular.' },
      { id: 'l4-e4', type: 'matching', question: 'Match contractions.', pairs: [{ french: 'de + le', english: 'du' }, { french: 'à + le', english: 'au' }, { french: 'de + les', english: 'des' }, { french: 'à + les', english: 'aux' }], explanation: 'These are contractions, not optional spellings.' },
      { id: 'l4-e5', type: 'multiple_choice', question: 'What is the regular plural of livre?', options: ['livres', 'livreaux', 'livrent'], correct_answer: 'livres', explanation: 'Most nouns add -s in writing.' },
      { id: 'l4-e6', type: 'matching', question: 'Match nouns to articles.', pairs: [{ french: 'le', english: 'marché' }, { french: 'la', english: 'table' }, { french: "l'", english: 'école' }, { french: 'les', english: 'sacs' }], explanation: 'Choose by gender, number, and first sound.' },
      { id: 'l4-e7', type: 'translation', question: 'EN→FR: The bakery is here.', direction: 'en_to_fr', correct_answer: 'La boulangerie est ici.', explanation: 'Boulangerie is feminine.' },
      { id: 'l4-e8', type: 'fill_blank', question: 'J’achète ___ légumes.', correct_answer: 'des', explanation: 'Use des for plural indefinite nouns.' },
    ],
  }),

  makeBase(5, 'Adjectives', 'Les Adjectifs', 'Make adjectives agree in gender and number, and place common adjectives correctly.', 3, ['adjectives', 'agreement', 'apartment'], {
    learning_objectives: [
      'Make regular adjectives feminine and plural',
      'Recognize common irregular adjective forms',
      'Place BAGS adjectives before the noun',
      'Describe apartments with accurate agreement',
    ],
    prerequisite_lessons: ['beginner-4'],
    dialogue: {
      title: 'Un appartement à louer',
      context: 'Two flatmates compare apartment listings and describe what they see.',
      exchanges: [
        { speaker: 'Inès', french: 'Le nouvel appartement est grand.', english: 'The new apartment is big.', pronunciation: 'luh noo-VEL ah-part-mahn ay grahn' },
        { speaker: 'Tom', french: 'Oui, mais la cuisine est petite.', english: 'Yes, but the kitchen is small.', pronunciation: 'wee meh lah kwee-ZEEN ay puh-TEET' },
        { speaker: 'Inès', french: 'Les chambres sont belles.', english: 'The bedrooms are beautiful.', pronunciation: 'lay SHAHM-bruh sohn bel' },
        { speaker: 'Tom', french: 'Et le salon est très lumineux.', english: 'And the living room is very bright.', pronunciation: 'ay luh sa-LOHN ay tray loo-mee-NUH' },
        { speaker: 'Inès', french: 'Le vieux quartier est intéressant.', english: 'The old neighborhood is interesting.', pronunciation: 'luh vyuh kar-TYAY ay an-tay-ray-SAHN' },
        { speaker: 'Tom', french: 'Mais les loyers sont chers.', english: 'But the rents are expensive.', pronunciation: 'meh lay lwa-YAY sohn shehr' },
        { speaker: 'Inès', french: 'Une bonne adresse est rare.', english: 'A good address is rare.', pronunciation: 'oon bun ah-DRES ay rahr' },
        { speaker: 'Tom', french: 'Alors, nous regardons une autre annonce.', english: 'So, we look at another listing.', pronunciation: 'ah-LOR noo ruh-gar-DOHN oon ohtr ah-NOHNS' },
      ],
      cultural_notes: [
        'French rental ads often abbreviate room counts: T1, T2, T3 indicate the number of main rooms, excluding kitchen and bathroom.',
        'In large cities, “lumineux” is a practical selling point because many older apartments have small windows or interior courtyards.',
        'Listings commonly mention the étage and whether there is an ascenseur, especially in older Parisian buildings.',
      ],
    },
    grammar: {
      topic: 'Adjective Agreement and Placement',
      explanation: 'French adjectives usually agree with the noun they describe. If the noun is feminine, many adjectives add -e; if it is plural, many add -s. This agreement is visible in writing even when the pronunciation barely changes.\n\nMost descriptive adjectives come after the noun, but a small group of very common adjectives usually comes before it: beauty, age, goodness, and size. That is why you see une petite cuisine but une cuisine lumineuse.',
      examples: [
        { french: 'un appartement cher', english: 'an expensive apartment', pronunciation: 'uhn ah-part-mahn shehr', highlight: 'cher' },
        { french: 'une petite cuisine', english: 'a small kitchen', pronunciation: 'oon puh-TEET kwee-ZEEN', highlight: 'petite' },
        { french: 'des chambres belles', english: 'beautiful bedrooms', pronunciation: 'day SHAHM-bruh bel', highlight: 'belles' },
      ],
      patterns: ['masculine: grand', 'feminine: grande', 'plural: grands/grandes', 'most adjectives follow the noun', 'BAGS adjectives usually precede the noun', 'beau/nouveau/vieux have special vowel forms'],
      tip: 'Remember BAGS: Beauty, Age, Goodness, Size. These frequent adjectives usually go before the noun.',
    },
    vocabulary: [
      v('grand / grande', 'big / tall', 'grahn / grahnd', 'Le salon est grand.', 'The living room is big.', 'adjectives'),
      v('petit / petite', 'small', 'puh-TEE / puh-TEET', 'La cuisine est petite.', 'The kitchen is small.', 'adjectives'),
      v('beau / belle', 'beautiful', 'boh / bel', 'Les chambres sont belles.', 'The bedrooms are beautiful.', 'adjectives'),
      v('bon / bonne', 'good', 'bohn / bun', 'Une bonne adresse est rare.', 'A good address is rare.', 'adjectives'),
      v('mauvais / mauvaise', 'bad', 'moh-VEH / moh-VEZ', 'Le quartier est mauvais.', 'The neighborhood is bad.', 'adjectives'),
      v('nouveau / nouvelle', 'new', 'noo-VOH / noo-VEL', 'Le nouvel appartement est grand.', 'The new apartment is big.', 'adjectives'),
      v('vieux / vieille', 'old', 'vyuh / vyeh-yuh', 'Le vieux quartier est intéressant.', 'The old neighborhood is interesting.', 'adjectives'),
      v('jeune', 'young', 'zhuhn', 'La jeune voisine est ici.', 'The young neighbor is here.', 'adjectives'),
      v('long / longue', 'long', 'lohn / long', 'La rue est longue.', 'The street is long.', 'adjectives'),
      v('court / courte', 'short', 'koor / koort', 'La visite est courte.', 'The visit is short.', 'adjectives'),
      v('chaud / chaude', 'warm / hot', 'shoh / shohd', 'La chambre est chaude.', 'The bedroom is warm.', 'adjectives'),
      v('froid / froide', 'cold', 'frwah / frwahd', 'La pièce est froide.', 'The room is cold.', 'adjectives'),
      v('rapide', 'fast', 'rah-PEED', 'La visite est rapide.', 'The visit is fast.', 'adjectives'),
      v('lent / lente', 'slow', 'lahn / lahnt', 'Le bus est lent.', 'The bus is slow.', 'adjectives'),
      v('cher / chère', 'expensive', 'shehr', 'Les loyers sont chers.', 'The rents are expensive.', 'adjectives'),
      v('facile', 'easy', 'fah-SEEL', 'La décision est facile.', 'The decision is easy.', 'adjectives'),
      v('difficile', 'difficult', 'dee-fee-SEEL', 'Le choix est difficile.', 'The choice is difficult.', 'adjectives'),
      v('intéressant / intéressante', 'interesting', 'an-tay-ray-SAHN / an-tay-ray-SAHNT', 'Le quartier est intéressant.', 'The neighborhood is interesting.', 'adjectives'),
      v('ennuyeux / ennuyeuse', 'boring', 'ahn-nwee-YUH / ahn-nwee-YUHZ', 'La visite est ennuyeuse.', 'The visit is boring.', 'adjectives'),
      v('lumineux / lumineuse', 'bright', 'loo-mee-NUH / loo-mee-NUHZ', 'La pièce est lumineuse.', 'The room is bright.', 'adjectives'),
    ],
    exercises: [
      { id: 'l5-e1', type: 'transformation', question: 'Change masculine adjectives to feminine.', instruction: 'masculine_to_feminine', items: [{ original: 'grand', transformed: 'grande', translation: 'big' }, { original: 'petit', transformed: 'petite', translation: 'small' }, { original: 'cher', transformed: 'chère', translation: 'expensive' }], explanation: 'Most feminine adjective forms add -e, with spelling or accent changes when needed.' },
      { id: 'l5-e2', type: 'transformation', question: 'Change singular phrases to plural.', instruction: 'singular_to_plural', items: [{ original: 'un grand salon', transformed: 'des grands salons', translation: 'big living rooms' }, { original: 'une petite chambre', transformed: 'des petites chambres', translation: 'small bedrooms' }], explanation: 'Plural nouns and adjectives usually add -s.' },
      { id: 'l5-e3', type: 'fill_blank', question: 'La cuisine est ___.', correct_answer: 'petite', explanation: 'Cuisine is feminine, so petit becomes petite.' },
      { id: 'l5-e4', type: 'multiple_choice', question: 'Which adjective usually goes before the noun?', options: ['rouge', 'petit', 'intéressant'], correct_answer: 'petit', explanation: 'Size adjectives are BAGS adjectives.' },
      { id: 'l5-e5', type: 'matching', question: 'Match adjectives to antonyms.', pairs: [{ french: 'grand', english: 'petit' }, { french: 'bon', english: 'mauvais' }, { french: 'rapide', english: 'lent' }, { french: 'facile', english: 'difficile' }], explanation: 'Learning adjective pairs builds useful contrast.' },
      { id: 'l5-e6', type: 'translation', question: 'EN→FR: The new apartment is big.', direction: 'en_to_fr', correct_answer: "Le nouvel appartement est grand.", explanation: 'Use nouvel before a masculine vowel-starting noun.' },
      { id: 'l5-e7', type: 'translation', question: 'EN→FR: The rooms are beautiful.', direction: 'en_to_fr', correct_answer: 'Les chambres sont belles.', explanation: 'Chambres is feminine plural, so belles.' },
      { id: 'l5-e8', type: 'fill_blank', question: 'Les loyers sont ___.', correct_answer: 'chers', explanation: 'Loyers is masculine plural, so cher becomes chers.' },
    ],
  }),

  makeBase(6, 'Possessive Adjectives', 'Les Adjectifs Possessifs', 'Use mon, ma, mes and the full possessive adjective system with family vocabulary.', 3, ['possessives', 'family'], {
    learning_objectives: [
      'Choose the correct possessive adjective for a noun',
      'Explain why possessives agree with the noun, not the owner',
      'Use family vocabulary in short descriptions',
      'Use mon before feminine nouns that begin with a vowel sound',
    ],
    prerequisite_lessons: ['beginner-5'],
    dialogue: {
      title: 'Un dîner en famille',
      context: 'At a family dinner, relatives introduce people around the table.',
      exchanges: [
        { speaker: 'Camille', french: 'Voici mon père et ma mère.', english: 'Here are my father and my mother.', pronunciation: 'vwah-SEE mohn pehr ay mah mehr' },
        { speaker: 'Noah', french: 'Votre père est très sympa.', english: 'Your father is very nice.', pronunciation: 'votr pehr ay tray sam-PAH' },
        { speaker: 'Camille', french: 'Merci. Ma sœur habite à Lyon.', english: 'Thanks. My sister lives in Lyon.', pronunciation: 'mer-SEE mah suhr ah-BEET ah lee-OHN' },
        { speaker: 'Noah', french: 'Et ton frère?', english: 'And your brother?', pronunciation: 'ay tohn frehr' },
        { speaker: 'Camille', french: 'Mon frère travaille ici.', english: 'My brother works here.', pronunciation: 'mohn frehr tra-VIE ee-SEE' },
        { speaker: 'Noah', french: 'Leur maison est belle.', english: 'Their house is beautiful.', pronunciation: 'luhr meh-ZOHN ay bel' },
        { speaker: 'Camille', french: 'Oui, et nos cousins sont jeunes.', english: 'Yes, and our cousins are young.', pronunciation: 'wee ay noh koo-ZAN sohn zhuhn' },
        { speaker: 'Noah', french: 'Votre famille est grande.', english: 'Your family is big.', pronunciation: 'votr fa-MEE ay grahnd' },
      ],
      cultural_notes: [
        'Family meals in France often keep several generations in one conversation, especially on Sundays and holidays.',
        'Voici is a fixed presentation word meaning “here is / here are”; it is useful before you formally study demonstratives.',
        'Possessives are frequent because French avoids repeating “de + person” once ownership is clear.',
      ],
    },
    grammar: {
      topic: 'Possessive Adjectives',
      explanation: 'Possessive adjectives tell whose noun it is: my, your, his, her, our, their. In French, the form agrees with the noun being owned, not with the owner. Mon frère uses mon because frère is masculine; ma mère uses ma because mère is feminine.\n\nThis is why son père can mean his father or her father. Son agrees with père. Context tells you who the owner is.',
      examples: [
        { french: 'mon père', english: 'my father', pronunciation: 'mohn pehr', highlight: 'mon' },
        { french: 'ma sœur', english: 'my sister', pronunciation: 'mah suhr', highlight: 'ma' },
        { french: 'leurs enfants', english: 'their children', pronunciation: 'luhr zahn-FAHN', highlight: 'leurs' },
      ],
      patterns: ['mon/ma/mes', 'ton/ta/tes', 'son/sa/ses', 'notre/nos', 'votre/vos', 'leur/leurs'],
      tip: 'The biggest mistake is matching the possessor. Sa mère can be his mother or her mother because mère is feminine.',
    },
    vocabulary: [
      v('le père', 'father', 'luh pehr', 'Mon père est ici.', 'My father is here.', 'family', 'masculine'),
      v('la mère', 'mother', 'lah mehr', 'Ma mère est ici.', 'My mother is here.', 'family', 'feminine'),
      v('le frère', 'brother', 'luh frehr', 'Ton frère travaille.', 'Your brother works.', 'family', 'masculine'),
      v('la sœur', 'sister', 'lah suhr', 'Ma sœur habite à Lyon.', 'My sister lives in Lyon.', 'family', 'feminine'),
      v('le fils', 'son', 'luh fees', 'Son fils est jeune.', 'His son is young.', 'family', 'masculine'),
      v('la fille', 'daughter / girl', 'lah fee', 'Sa fille est étudiante.', 'Her daughter is a student.', 'family', 'feminine'),
      v('le grand-père', 'grandfather', 'luh grahn-pehr', 'Mon grand-père est français.', 'My grandfather is French.', 'family', 'masculine'),
      v('la grand-mère', 'grandmother', 'lah grahn-mehr', 'Ma grand-mère est française.', 'My grandmother is French.', 'family', 'feminine'),
      v("l'oncle", 'uncle', 'lohnkl', 'Mon oncle est professeur.', 'My uncle is a teacher.', 'family', 'masculine'),
      v('la tante', 'aunt', 'lah tahnt', 'Ta tante est aimable.', 'Your aunt is kind.', 'family', 'feminine'),
      v('le cousin', 'male cousin', 'luh koo-ZAN', 'Notre cousin est jeune.', 'Our cousin is young.', 'family', 'masculine'),
      v('la cousine', 'female cousin', 'lah koo-ZEEN', 'Notre cousine est jeune.', 'Our cousin is young.', 'family', 'feminine'),
      v('le mari', 'husband', 'luh ma-REE', 'Son mari est médecin.', 'Her husband is a doctor.', 'family', 'masculine'),
      v('la femme', 'wife / woman', 'lah fam', 'Sa femme est ingénieure.', 'His wife is an engineer.', 'family', 'feminine'),
      v("l'enfant", 'child', 'lahn-FAHN', 'Mon enfant est ici.', 'My child is here.', 'family', 'masculine'),
      v('la maison', 'house', 'lah meh-ZOHN', 'Leur maison est belle.', 'Their house is beautiful.', 'objects', 'feminine'),
      v("l'appartement", 'apartment', 'lah-part-mahn', 'Votre appartement est grand.', 'Your apartment is big.', 'objects', 'masculine'),
      v('la voiture', 'car', 'lah vwah-TOOR', 'Sa voiture est rapide.', 'His car is fast.', 'objects', 'feminine'),
      v('la chambre', 'bedroom', 'lah SHAHM-bruh', 'Ma chambre est petite.', 'My room is small.', 'objects', 'feminine'),
      v('le travail', 'work / job', 'luh tra-VIE', 'Son travail est intéressant.', 'Her work is interesting.', 'objects', 'masculine'),
    ],
    exercises: [
      { id: 'l6-e1', type: 'fill_blank', question: '___ mère est française. (my)', correct_answer: 'Ma', explanation: 'Mère is feminine singular.' },
      { id: 'l6-e2', type: 'fill_blank', question: '___ enfants sont ici. (their)', correct_answer: 'Leurs', explanation: 'Enfants is plural, so use leurs.' },
      { id: 'l6-e3', type: 'transformation', question: 'Replace “de Marie” with a possessive adjective.', instruction: 'informal_to_formal', items: [{ original: 'le père de Marie', transformed: 'son père', translation: 'her father' }, { original: 'la maison de Marie', transformed: 'sa maison', translation: 'her house' }], explanation: 'Son/sa/ses agree with the noun.' },
      { id: 'l6-e4', type: 'multiple_choice', question: 'Which one fits voiture?', options: ['son', 'sa', 'ses'], correct_answer: 'sa', explanation: 'Voiture is feminine singular.' },
      { id: 'l6-e5', type: 'translation', question: 'EN→FR: My brother works here.', direction: 'en_to_fr', correct_answer: 'Mon frère travaille ici.', explanation: 'Frère is masculine, so mon.' },
      { id: 'l6-e6', type: 'gender_sort', question: 'Choose mon or ma by noun gender.', items: [{ word: 'père', gender: 'masculine', article: 'mon' }, { word: 'mère', gender: 'feminine', article: 'ma' }, { word: 'frère', gender: 'masculine', article: 'mon' }, { word: 'sœur', gender: 'feminine', article: 'ma' }], explanation: 'The possessive changes with the noun.' },
      { id: 'l6-e7', type: 'matching', question: 'Match possessive forms.', pairs: [{ french: 'mon', english: 'my + masculine singular' }, { french: 'ma', english: 'my + feminine singular' }, { french: 'mes', english: 'my + plural' }, { french: 'notre', english: 'our + singular' }], explanation: 'Person and noun form both matter.' },
      { id: 'l6-e8', type: 'speaking_prompt', question: 'Describe your family with possessives.', model_answer: 'Mon père est gentil, ma mère est française et mes cousins sont jeunes.', translation: 'My father is kind, my mother is French, and my cousins are young.', tip: 'Say the noun silently first, then choose the possessive.' },
    ],
  }),

  makeBase(7, 'Numbers and Time', "Les Nombres et l'Heure", 'Use numbers 1-69 and tell time for daily schedules.', 2, ['time', 'numbers', 'schedule'], {
    learning_objectives: [
      'Build numbers from 1 to 69',
      'Tell clock time with heures, et demie, and et quart',
      'Ask à quelle heure',
      'Describe a simple daily work schedule',
    ],
    prerequisite_lessons: ['beginner-6'],
    dialogue: {
      title: 'La journée au bureau',
      context: 'Colleagues coordinate meetings, lunch, and a train time during the workday.',
      exchanges: [
        { speaker: 'Maya', french: 'À quelle heure est votre réunion?', english: 'What time is your meeting?', pronunciation: 'ah kel uhr ay votr ray-oo-NYOHN' },
        { speaker: 'Éric', french: 'Elle est à neuf heures.', english: 'It is at nine o’clock.', pronunciation: 'el ay ah nuhf uhr' },
        { speaker: 'Maya', french: 'Mon rendez-vous est à onze heures et demie.', english: 'My appointment is at eleven thirty.', pronunciation: 'mohn rahn-day-VOO ay ah onz uhr ay duh-MEE' },
        { speaker: 'Éric', french: 'Nous avons le déjeuner à midi.', english: 'We have lunch at noon.', pronunciation: 'noo zah-VOHN luh day-zhuh-NAY ah mee-DEE' },
        { speaker: 'Maya', french: 'Le train est à dix-huit heures quinze.', english: 'The train is at 18:15.', pronunciation: 'luh tran ay ah deez-weet uhr kanz' },
        { speaker: 'Éric', french: 'Très bien. Je travaille maintenant.', english: 'Very good. I am working now.', pronunciation: 'tray byahn zhuh tra-VIE man-tuh-NAHN' },
        { speaker: 'Maya', french: 'Vous êtes en avance.', english: 'You are early.', pronunciation: 'voo zet ahn nah-VAHNS' },
        { speaker: 'Éric', french: 'Oui, je suis toujours à l’heure.', english: 'Yes, I am always on time.', pronunciation: 'wee zhuh swee too-ZHOOR ah luhr' },
      ],
      cultural_notes: [
        'Transport, office schedules, and television listings in France commonly use the 24-hour clock.',
        'Midi is noon; minuit is midnight. They are common words, not just formal clock labels.',
        'Être à l’heure is valued in professional settings, while social dinners can allow more flexibility.',
      ],
    },
    grammar: {
      topic: 'Numbers 1-69 and Telling Time',
      explanation: 'French numbers from 1 to 69 are the base for time, schedules, prices, and addresses. For the clock, use il est plus the hour: il est neuf heures. For scheduled events, use à: la réunion est à neuf heures.\n\nOfficial timetables often use the 24-hour clock, especially trains, appointments, and public information. In casual speech, people also use context such as du matin, de l’après-midi, or du soir.',
      examples: [
        { french: 'Il est neuf heures.', english: 'It is nine o’clock.', pronunciation: 'eel ay nuhf uhr', highlight: 'heures' },
        { french: 'Il est dix heures et demie.', english: 'It is ten thirty.', pronunciation: 'eel ay deez uhr ay duh-MEE', highlight: 'et demie' },
        { french: 'À quelle heure est la réunion?', english: 'What time is the meeting?', pronunciation: 'ah kel uhr ay lah ray-oo-NYOHN', highlight: 'À quelle heure' },
      ],
      patterns: ['1-16 have special forms', '17-19 combine dix plus number', '20-69 use tens plus units', 'Il est X heures', 'et demie = half past', 'et quart = quarter past'],
      tip: 'Official French times use 24-hour format. Dix-huit heures trente is normal for 18:30.',
    },
    vocabulary: [
      v('vingt et un', 'twenty-one', 'van tay uhn', 'Il est vingt et une heures.', 'It is 21:00.', 'numbers'),
      v('trente', 'thirty', 'trahnt', 'J’ai trente ans.', 'I am thirty.', 'numbers'),
      v('quarante', 'forty', 'kah-RAHNT', 'Il est quarante minutes.', 'It is forty minutes.', 'numbers'),
      v('cinquante', 'fifty', 'san-KAHNT', 'J’ai cinquante euros.', 'I have fifty euros.', 'numbers'),
      v('soixante', 'sixty', 'swah-SAHNT', 'Le rendez-vous est à soixante minutes.', 'The appointment is in sixty minutes.', 'numbers'),
      v('heure', 'hour / o’clock', 'uhr', 'Il est neuf heures.', 'It is nine o’clock.', 'time', 'feminine'),
      v('et demie', 'half past', 'ay duh-MEE', 'Il est dix heures et demie.', 'It is ten thirty.', 'time'),
      v('et quart', 'quarter past', 'ay kar', 'Il est huit heures et quart.', 'It is quarter past eight.', 'time'),
      v('moins le quart', 'quarter to', 'mwahn luh kar', 'Il est neuf heures moins le quart.', 'It is quarter to nine.', 'time'),
      v('matin', 'morning', 'mah-TAN', 'Le matin est froid.', 'The morning is cold.', 'time', 'masculine'),
      v('après-midi', 'afternoon', 'ah-preh mee-DEE', "L'après-midi est long.", 'The afternoon is long.', 'time', 'masculine'),
      v('soir', 'evening', 'swahr', 'Le soir est calme.', 'The evening is calm.', 'time', 'masculine'),
      v('nuit', 'night', 'nwee', 'La nuit est froide.', 'The night is cold.', 'time', 'feminine'),
      v('tôt', 'early', 'toh', 'Je suis tôt.', 'I am early.', 'time'),
      v('tard', 'late', 'tar', 'Vous êtes tard.', 'You are late.', 'time'),
      v('en avance', 'early / ahead of time', 'ahn nah-VAHNS', 'Vous êtes en avance.', 'You are early.', 'time'),
      v('en retard', 'late', 'ahn ruh-TAR', 'Nous sommes en retard.', 'We are late.', 'time'),
      v("à l'heure", 'on time', 'ah luhr', "Je suis à l'heure.", 'I am on time.', 'time'),
      v('lundi', 'Monday', 'luhn-DEE', 'Lundi est utile.', 'Monday is useful.', 'days'),
      v('vendredi', 'Friday', 'vahn-druh-DEE', 'Vendredi est ici.', 'Friday is here.', 'days'),
    ],
    exercises: [
      { id: 'l7-e1', type: 'matching', question: 'Match written numbers to digits.', pairs: [{ french: 'trente', english: '30' }, { french: 'quarante', english: '40' }, { french: 'cinquante', english: '50' }, { french: 'soixante', english: '60' }], explanation: 'Tens build the 20-69 range.' },
      { id: 'l7-e2', type: 'fill_blank', question: '42 = quarante-___.', correct_answer: 'deux', explanation: '42 is forty-two.' },
      { id: 'l7-e3', type: 'multiple_choice', question: 'Which means 9:30?', options: ['neuf heures et demie', 'neuf heures et quart', 'neuf heures moins le quart'], correct_answer: 'neuf heures et demie', explanation: 'Et demie means half past.' },
      { id: 'l7-e4', type: 'fill_blank', question: 'Il est dix ___ et ___.', correct_answer: ['heures et demie', 'heures et demie.'], explanation: 'The common phrase is dix heures et demie.' },
      { id: 'l7-e5', type: 'translation', question: 'EN→FR: The meeting is at nine o’clock.', direction: 'en_to_fr', correct_answer: 'La réunion est à neuf heures.', explanation: 'Use à for scheduled time.' },
      { id: 'l7-e6', type: 'translation', question: 'EN→FR: I am on time.', direction: 'en_to_fr', correct_answer: "Je suis à l’heure.", explanation: 'Être à l’heure is the fixed phrase.' },
      { id: 'l7-e7', type: 'multiple_choice', question: 'Which format is common for French transport?', options: ['24-hour clock', 'only 12-hour clock', 'Roman numerals'], correct_answer: '24-hour clock', explanation: 'Transport schedules normally use 24-hour time.' },
      { id: 'l7-e8', type: 'speaking_prompt', question: 'Say one work appointment time.', model_answer: 'Mon rendez-vous est à quatorze heures trente.', translation: 'My appointment is at 14:30.', tip: 'Use à before the scheduled time.' },
    ],
  }),

  makeBase(8, 'Partitives and Food', 'Les Articles Partitifs et la Nourriture', 'Use du, de la, de l’, des for food and switch to de after negation or quantity.', 3, ['partitives', 'food', 'shopping'], {
    learning_objectives: [
      'Choose partitive articles for portions and uncountable food',
      'Contrast un/une/des with du/de la/de l’',
      'Use de after negation and quantities',
      'Use common grocery vocabulary',
    ],
    prerequisite_lessons: ['beginner-7'],
    dialogue: {
      title: 'Les courses',
      context: 'Flatmates plan grocery shopping and talk about what they have and do not have.',
      exchanges: [
        { speaker: 'Lina', french: 'Nous achetons du pain et du fromage?', english: 'Are we buying bread and cheese?', pronunciation: 'noo zahsh-TOHN doo pan ay doo fro-MAZH' },
        { speaker: 'Samir', french: 'Oui, et de la viande pour ce soir.', english: 'Yes, and some meat for tonight.', pronunciation: 'wee ay duh lah vee-AHND poor suh swahr' },
        { speaker: 'Lina', french: 'Je mange des légumes, mais pas de viande.', english: 'I eat vegetables, but no meat.', pronunciation: 'zhuh mahnzh day lay-GOOM meh pah duh vee-AHND' },
        { speaker: 'Samir', french: 'Alors, des tomates et des carottes.', english: 'So, tomatoes and carrots.', pronunciation: 'ah-LOR day toh-MAT ay day kah-ROT' },
        { speaker: 'Lina', french: 'Nous avons de l’eau?', english: 'Do we have water?', pronunciation: 'noo zah-VOHN duh loh' },
        { speaker: 'Samir', french: 'Non, nous n’avons pas d’eau.', english: 'No, we do not have water.', pronunciation: 'nohn noo nah-VOHN pah doh' },
        { speaker: 'Lina', french: 'Je prends du café.', english: 'I’ll take coffee.', pronunciation: 'zhuh prahn doo kah-FAY' },
        { speaker: 'Samir', french: 'Et moi, je voudrais du thé.', english: 'And I would like tea.', pronunciation: 'ay mwah zhuh voo-DREH doo tay' },
      ],
      cultural_notes: [
        'French grocery shopping often combines supermarkets with specialized shops and weekly markets depending on neighborhood access.',
        'Je prends is a practical fixed phrase for selecting food or drinks; it is common at counters and cafés.',
        'Je voudrais is presented here only as a polite ordering phrase. The conditional grammar behind it is B1-level.',
      ],
    },
    grammar: {
      topic: 'Partitive Articles',
      explanation: 'Partitive articles are used when you mean an unspecified amount of something, especially food and drink. English often says “some” or uses no article at all, but French needs one: du pain, de la viande, de l’eau.\n\nThe form depends on gender and sound: du for masculine, de la for feminine, de l’ before a vowel sound, and des for plural. After a negative or after quantity expressions, the article usually reduces to de or d’: pas de pain, beaucoup d’eau.',
      examples: [
        { french: 'Je mange du pain.', english: 'I eat bread.', pronunciation: 'zhuh mahnzh doo pan', highlight: 'du' },
        { french: 'Nous avons de l’eau.', english: 'We have water.', pronunciation: 'noo zah-VOHN duh loh', highlight: "de l’" },
        { french: 'Je ne mange pas de viande.', english: 'I do not eat meat.', pronunciation: 'zhuh nuh mahnzh pah duh vee-AHND', highlight: 'pas de' },
      ],
      patterns: ['du masculine', 'de la feminine', "de l’ before vowel or silent h", 'des plural portions', 'after negation use de/d’', 'after quantities use de/d’'],
      tip: 'After ne...pas and expressions of quantity, the partitive shrinks to de: Je bois du café, but Je ne bois pas de café.',
    },
    vocabulary: [
      v('le pain', 'bread', 'luh pan', 'Je mange du pain.', 'I eat bread.', 'food', 'masculine'),
      v('le beurre', 'butter', 'luh buhr', 'Nous avons du beurre.', 'We have butter.', 'food', 'masculine'),
      v('le fromage', 'cheese', 'luh fro-MAZH', 'Je mange du fromage.', 'I eat cheese.', 'food', 'masculine'),
      v('la viande', 'meat', 'lah vee-AHND', 'Je ne mange pas de viande.', 'I do not eat meat.', 'food', 'feminine'),
      v('le poulet', 'chicken', 'luh poo-LEH', 'Nous achetons du poulet.', 'We buy chicken.', 'food', 'masculine'),
      v('le poisson', 'fish', 'luh pwah-SOHN', 'Elle mange du poisson.', 'She eats fish.', 'food', 'masculine'),
      v('la tomate', 'tomato', 'lah toh-MAT', 'J’achète des tomates.', 'I buy tomatoes.', 'food', 'feminine'),
      v('la carotte', 'carrot', 'lah kah-ROT', 'Tu manges des carottes.', 'You eat carrots.', 'food', 'feminine'),
      v('le haricot', 'bean', 'luh ah-ree-KOH', 'Nous avons des haricots.', 'We have beans.', 'food', 'masculine'),
      v('la pomme', 'apple', 'lah pum', 'Je mange une pomme.', 'I eat an apple.', 'food', 'feminine'),
      v('la banane', 'banana', 'lah ba-NAN', 'Elle achète des bananes.', 'She buys bananas.', 'food', 'feminine'),
      v('le raisin', 'grapes', 'luh reh-ZAN', 'Nous avons du raisin.', 'We have grapes.', 'food', 'masculine'),
      v("l'eau", 'water', 'loh', 'Je bois de l’eau.', 'I drink water.', 'drinks', 'feminine'),
      v('le lait', 'milk', 'luh leh', 'Tu prends du lait.', 'You take milk.', 'drinks', 'masculine'),
      v('le jus', 'juice', 'luh zhoo', 'Il prend du jus.', 'He takes juice.', 'drinks', 'masculine'),
      v('le café', 'coffee', 'luh kah-FAY', 'Je prends du café.', 'I take coffee.', 'drinks', 'masculine'),
      v('le thé', 'tea', 'luh tay', 'Je voudrais du thé.', 'I would like tea.', 'drinks', 'masculine'),
      v('le sucre', 'sugar', 'luh SOO-kruh', 'Je prends du sucre.', 'I take sugar.', 'food', 'masculine'),
      v('le sel', 'salt', 'luh sel', 'Nous avons du sel.', 'We have salt.', 'food', 'masculine'),
      v("l'huile", 'oil', 'lweel', 'J’achète de l’huile.', 'I buy oil.', 'food', 'feminine'),
    ],
    exercises: [
      { id: 'l8-e1', type: 'fill_blank', question: 'Je mange ___ pain.', correct_answer: 'du', explanation: 'Pain is masculine and used as an unspecified amount.' },
      { id: 'l8-e2', type: 'transformation', question: 'Make the partitive sentence negative.', instruction: 'affirmative_to_negative', items: [{ original: 'Je mange du pain.', transformed: 'Je ne mange pas de pain.', translation: 'I do not eat bread.' }, { original: 'Nous avons de l’eau.', transformed: 'Nous n’avons pas d’eau.', translation: 'We do not have water.' }], explanation: 'Partitives become de/d’ after negation.' },
      { id: 'l8-e3', type: 'multiple_choice', question: 'Which fits an unspecified amount of meat?', options: ['un viande', 'de la viande', 'du viande'], correct_answer: 'de la viande', explanation: 'Viande is feminine and uncountable in this context.' },
      { id: 'l8-e4', type: 'matching', question: 'Match food categories.', pairs: [{ french: 'pomme', english: 'fruit' }, { french: 'carotte', english: 'vegetable' }, { french: 'café', english: 'drink' }, { french: 'poulet', english: 'meat' }], explanation: 'Food categories help anticipate articles.' },
      { id: 'l8-e5', type: 'translation', question: 'EN→FR: We do not have water.', direction: 'en_to_fr', correct_answer: "Nous n’avons pas d’eau.", explanation: 'Use d’ before a vowel after pas.' },
      { id: 'l8-e6', type: 'gender_sort', question: 'Sort food nouns by gender.', items: [{ word: 'pain', gender: 'masculine', article: 'le' }, { word: 'viande', gender: 'feminine', article: 'la' }, { word: 'tomate', gender: 'feminine', article: 'la' }, { word: 'café', gender: 'masculine', article: 'le' }], explanation: 'Gender determines du or de la.' },
      { id: 'l8-e7', type: 'fill_blank', question: 'Je voudrais ___ thé.', correct_answer: 'du', explanation: 'Thé is masculine; je voudrais is a fixed polite phrase here.' },
      { id: 'l8-e8', type: 'speaking_prompt', question: 'Say three grocery items you need.', model_answer: 'J’achète du pain, de la viande et des tomates.', translation: 'I buy bread, meat, and tomatoes.', tip: 'Use partitives for unspecified amounts.' },
    ],
  }),

  makeBase(9, 'Negation and Questions', 'La Négation et les Questions', 'Build negative sentences and ask questions with intonation, est-ce que, inversion, and question words.', 3, ['negation', 'questions'], {
    learning_objectives: [
      'Place ne and pas around a conjugated verb',
      'Use n’ before vowel sounds',
      'Ask questions with intonation and est-ce que',
      'Choose common interrogative words',
    ],
    prerequisite_lessons: ['beginner-8'],
    dialogue: {
      title: 'Dans le couloir',
      context: 'Two neighbours chat in the building hallway, asking questions and giving negative answers.',
      exchanges: [
        { speaker: 'Julie', french: 'Tu travailles aujourd’hui?', english: 'Are you working today?', pronunciation: 'too tra-VIE oh-zhoor-DWEE' },
        { speaker: 'Karim', french: 'Non, je ne travaille pas.', english: 'No, I am not working.', pronunciation: 'nohn zhuh nuh tra-VIE pah' },
        { speaker: 'Julie', french: 'Est-ce que tu regardes le match ce soir?', english: 'Are you watching the match tonight?', pronunciation: 'es-kuh too ruh-GARD luh match suh swahr' },
        { speaker: 'Karim', french: 'Non, je n’aime pas le football.', english: 'No, I do not like football.', pronunciation: 'nohn zhuh nem pah luh foot-BOL' },
        { speaker: 'Julie', french: 'Qu’est-ce que tu aimes?', english: 'What do you like?', pronunciation: 'kes-kuh too zem' },
        { speaker: 'Karim', french: 'J’aime le cinéma et la musique.', english: 'I like cinema and music.', pronunciation: 'zhem luh see-nay-MAH ay lah moo-ZEEK' },
        { speaker: 'Julie', french: 'Où habites-tu exactement?', english: 'Where do you live exactly?', pronunciation: 'oo ah-beet TOO egz-ak-tuh-MAHN' },
        { speaker: 'Karim', french: 'J’habite au troisième étage.', english: 'I live on the third floor.', pronunciation: 'zha-BEET oh trwah-ZYEM ay-TAHZH' },
        { speaker: 'Julie', french: 'Pourquoi tu ne marches pas?', english: 'Why aren’t you walking?', pronunciation: 'poor-KWAH too nuh marsh pah' },
        { speaker: 'Karim', french: 'Parce que j’ai froid.', english: 'Because I am cold.', pronunciation: 'pars-kuh zhay frwah' },
      ],
      cultural_notes: [
        'In spoken French, intonation questions are very common in casual neighbourly conversations.',
        'The written ne is often dropped in speech, but learners should write both ne and pas.',
        'Inversion such as habites-tu is formal and useful for recognition, even when est-ce que is safer for beginners.',
      ],
    },
    grammar: {
      topic: 'Negation and Question Forms',
      explanation: 'The basic French negative wraps around the conjugated verb: ne before it and pas after it. Before a vowel sound, ne becomes n’: je n’aime pas. In informal speech people often drop ne, but careful written French keeps both parts.\n\nFrench questions have three common forms. Intonation keeps statement order, est-ce que adds a question marker, and inversion switches the subject and verb in more formal French.',
      examples: [
        { french: 'Je ne travaille pas.', english: 'I do not work.', pronunciation: 'zhuh nuh tra-VIE pah', highlight: 'ne...pas' },
        { french: 'Est-ce que tu parles français?', english: 'Do you speak French?', pronunciation: 'es-kuh too parl frahn-SAY', highlight: 'Est-ce que' },
        { french: 'Où habitez-vous?', english: 'Where do you live?', pronunciation: 'oo ah-bee-TAY voo', highlight: 'Où' },
      ],
      patterns: ['ne + verb + pas', "ne becomes n’ before a vowel", 'intonation: Tu parles français?', 'est-ce que + statement order', 'inversion is more formal', 'question word + question form'],
      tip: 'In casual speech, natives often drop ne. Write both parts, but expect to hear Je sais pas instead of Je ne sais pas.',
    },
    vocabulary: [
      v('où', 'where', 'oo', 'Où habitez-vous?', 'Where do you live?', 'questions'),
      v('quand', 'when', 'kahn', 'Quand travaillez-vous?', 'When do you work?', 'questions'),
      v('pourquoi', 'why', 'poor-KWAH', 'Pourquoi tu ne travailles pas?', 'Why aren’t you working?', 'questions'),
      v('comment', 'how', 'koh-MAHN', 'Comment allez-vous?', 'How are you?', 'questions'),
      v('qui', 'who', 'kee', 'Qui est ici?', 'Who is here?', 'questions'),
      v('que', 'what', 'kuh', 'Que regardes-tu?', 'What are you watching?', 'questions'),
      v('combien', 'how much / how many', 'kohm-BYAN', 'Combien de livres avez-vous?', 'How many books do you have?', 'questions'),
      v('est-ce que', 'question marker', 'es-kuh', 'Est-ce que tu parles français?', 'Do you speak French?', 'questions'),
      v('ne...pas', 'not', 'nuh pah', 'Je ne travaille pas.', 'I do not work.', 'negation'),
      v("n'...pas", 'not before vowel', 'n pah', 'Je n’aime pas le football.', 'I do not like football.', 'negation'),
      v('ne...jamais', 'never', 'nuh zha-MEH', 'Je ne chante jamais.', 'I never sing.', 'negative preview'),
      v('ne...plus', 'no longer', 'nuh ploo', 'Je ne travaille plus ici.', 'I no longer work here.', 'negative preview'),
      v('ne...rien', 'nothing', 'nuh ree-AHN', 'Je ne regarde rien.', 'I watch nothing.', 'negative preview'),
      v('aussi', 'also', 'oh-SEE', 'J’aime aussi le cinéma.', 'I also like cinema.', 'connectors'),
      v('non plus', 'not either', 'nohn ploo', 'Moi non plus.', 'Me neither.', 'connectors'),
      v('si', 'yes, contrary to a negative', 'see', 'Si, je travaille.', 'Yes, I do work.', 'answers'),
    ],
    exercises: [
      { id: 'l9-e1', type: 'transformation', question: 'Make these sentences negative.', instruction: 'affirmative_to_negative', items: [{ original: 'Je travaille.', transformed: 'Je ne travaille pas.', translation: 'I do not work.' }, { original: 'Tu aimes le café.', transformed: 'Tu n’aimes pas le café.', translation: 'You do not like coffee.' }, { original: 'Nous regardons le film.', transformed: 'Nous ne regardons pas le film.', translation: 'We do not watch the film.' }], explanation: 'Put ne/n’ before the verb and pas after it.' },
      { id: 'l9-e2', type: 'fill_blank', question: 'Je ___ travaille ___ aujourd’hui.', correct_answer: ['ne pas', 'ne, pas'], explanation: 'The two negation words surround the verb.' },
      { id: 'l9-e3', type: 'multiple_choice', question: 'Which question word fits: ___ habites-tu? À Lyon.', options: ['Où', 'Quand', 'Pourquoi'], correct_answer: 'Où', explanation: 'À Lyon answers where.' },
      { id: 'l9-e4', type: 'matching', question: 'Match questions to answers.', pairs: [{ french: 'Où habites-tu?', english: 'À Paris.' }, { french: 'Quand travailles-tu?', english: 'Aujourd’hui.' }, { french: 'Combien de livres?', english: 'Trois.' }, { french: 'Pourquoi?', english: 'Parce que j’ai froid.' }], explanation: 'Question words predict answer type.' },
      { id: 'l9-e5', type: 'translation', question: 'EN→FR: Do you speak French?', direction: 'en_to_fr', correct_answer: ['Tu parles français?', 'Est-ce que tu parles français?', 'Parles-tu français?'], explanation: 'All three forms are possible.' },
      { id: 'l9-e6', type: 'translation', question: 'EN→FR: I do not like coffee.', direction: 'en_to_fr', correct_answer: 'Je n’aime pas le café.', explanation: 'Use n’ before aime.' },
      { id: 'l9-e7', type: 'fill_blank', question: '___ tu aimes le cinéma?', correct_answer: 'Est-ce que', explanation: 'Est-ce que turns statement order into a question.' },
      { id: 'l9-e8', type: 'speaking_prompt', question: 'Ask and answer one negative question.', model_answer: 'Tu travailles ce soir? Non, je ne travaille pas.', translation: 'Are you working tonight? No, I am not working.', tip: 'In speech, keep the rhythm light, but write both ne and pas.' },
    ],
  }),

  makeBase(10, 'Prepositions and Places', 'Les Prépositions et les Lieux', 'Describe location, city places, aller destinations, and il y a.', 3, ['places', 'prepositions', 'directions'], {
    learning_objectives: [
      'Use common prepositions of place',
      'Choose à, en, au, and aux for destinations',
      'Use il y a as a fixed there is / there are structure',
      'Give simple directions in a city',
    ],
    prerequisite_lessons: ['beginner-9'],
    dialogue: {
      title: 'Directions à Lyon',
      context: 'A tourist asks a local for directions to the station, a pharmacy, and a museum.',
      exchanges: [
        { speaker: 'Touriste', french: 'Bonjour, où est la gare?', english: 'Hello, where is the station?', pronunciation: 'bon-ZHOOR oo ay lah gar' },
        { speaker: 'Locale', french: 'La gare est près du musée.', english: 'The station is near the museum.', pronunciation: 'lah gar ay preh doo moo-ZAY' },
        { speaker: 'Touriste', french: 'Je vais à la gare maintenant.', english: 'I am going to the station now.', pronunciation: 'zhuh veh ah lah gar man-tuh-NAHN' },
        { speaker: 'Locale', french: 'Tournez à droite et traversez la rue.', english: 'Turn right and cross the street.', pronunciation: 'toor-NAY ah drwaht ay tra-vehr-SAY lah roo' },
        { speaker: 'Touriste', french: 'Il y a une pharmacie ici?', english: 'Is there a pharmacy here?', pronunciation: 'eel yah oon far-mah-SEE ee-SEE' },
        { speaker: 'Locale', french: 'Oui, il y a une pharmacie derrière la banque.', english: 'Yes, there is a pharmacy behind the bank.', pronunciation: 'wee eel yah oon far-mah-SEE deh-RYEHR lah bahnk' },
        { speaker: 'Touriste', french: 'Et le parc?', english: 'And the park?', pronunciation: 'ay luh park' },
        { speaker: 'Locale', french: 'Le parc est entre la mairie et la bibliothèque.', english: 'The park is between city hall and the library.', pronunciation: 'luh park ay ahntr lah meh-REE ay lah bee-blee-oh-TEK' },
        { speaker: 'Touriste', french: 'Merci, je continue tout droit.', english: 'Thanks, I continue straight ahead.', pronunciation: 'mer-SEE zhuh kon-tee-NOO too drwah' },
        { speaker: 'Locale', french: 'Oui, et vous allez au musée après.', english: 'Yes, and you go to the museum afterward.', pronunciation: 'wee ay voo zah-LAY oh moo-ZAY ah-PREH' },
      ],
      cultural_notes: [
        'French city centers often use landmarks such as mairie, gare, and pharmacie for directions.',
        'Pharmacies in France are highly visible because of their green cross signs and can give basic medical advice.',
        'À droite and à gauche are essential street-direction phrases; locals often combine them with landmarks.',
      ],
    },
    grammar: {
      topic: 'Prepositions, Aller, and Il y a',
      explanation: 'Prepositions show where something is in relation to something else: sur, sous, devant, derrière, entre, près de. They let you describe rooms, streets, landmarks, and directions without needing long sentences.\n\nFor destinations, aller combines with different forms: à for cities, au for masculine singular places with le, aux for plural places with les, and en for many feminine countries. Il y a is a fixed expression meaning “there is” or “there are.”',
      examples: [
        { french: 'La pharmacie est derrière la banque.', english: 'The pharmacy is behind the bank.', pronunciation: 'lah far-mah-SEE ay deh-RYEHR lah bahnk', highlight: 'derrière' },
        { french: 'Je vais au musée.', english: 'I am going to the museum.', pronunciation: 'zhuh veh oh moo-ZAY', highlight: 'au' },
        { french: 'Il y a une gare.', english: 'There is a station.', pronunciation: 'eel yah oon gar', highlight: 'Il y a' },
      ],
      patterns: ['à / dans / sur / sous', 'devant / derrière / entre', 'près de / loin de', 'à + city', 'au = à + le and aux = à + les', 'il y a is fixed'],
      conjugation_tables: [{ verb: 'aller', rows: [row('je', 'vais', 'veh'), row('tu', 'vas', 'vah'), row('il/elle/on', 'va', 'vah'), row('nous', 'allons', 'ah-LOHN'), row('vous', 'allez', 'ah-LAY'), row('ils/elles', 'vont', 'vohn')] }],
      tip: 'Cities never take an article: Je vais à Paris, not Je vais au Paris.',
    },
    vocabulary: [
      v('la gare', 'train station', 'lah gar', 'La gare est près du musée.', 'The station is near the museum.', 'city', 'feminine'),
      v("l'aéroport", 'airport', 'leh-roh-POR', "L'aéroport est loin.", 'The airport is far.', 'city', 'masculine'),
      v('le musée', 'museum', 'luh moo-ZAY', 'Je vais au musée.', 'I am going to the museum.', 'city', 'masculine'),
      v('la bibliothèque', 'library', 'lah bee-blee-oh-TEK', 'La bibliothèque est grande.', 'The library is big.', 'city', 'feminine'),
      v("l'hôpital", 'hospital', 'loh-pee-TAL', "L'hôpital est ici.", 'The hospital is here.', 'city', 'masculine'),
      v('la pharmacie', 'pharmacy', 'lah far-mah-SEE', 'Il y a une pharmacie.', 'There is a pharmacy.', 'city', 'feminine'),
      v('la banque', 'bank', 'lah bahnk', 'La pharmacie est derrière la banque.', 'The pharmacy is behind the bank.', 'city', 'feminine'),
      v('la poste', 'post office', 'lah post', 'La poste est près de la mairie.', 'The post office is near city hall.', 'city', 'feminine'),
      v('la mairie', 'city hall', 'lah meh-REE', 'La mairie est ancienne.', 'City hall is old.', 'city', 'feminine'),
      v("l'église", 'church', 'lay-GLEEZ', "L'église est devant le parc.", 'The church is in front of the park.', 'city', 'feminine'),
      v('le parc', 'park', 'luh park', 'Le parc est entre deux rues.', 'The park is between two streets.', 'city', 'masculine'),
      v('la rue', 'street', 'lah roo', 'Traversez la rue.', 'Cross the street.', 'directions', 'feminine'),
      v("l'avenue", 'avenue', 'lah-vuh-NOO', "L'avenue est longue.", 'The avenue is long.', 'directions', 'feminine'),
      v('le quartier', 'neighborhood', 'luh kar-TYAY', 'Le quartier est calme.', 'The neighborhood is quiet.', 'city', 'masculine'),
      v('tourner', 'to turn', 'toor-NAY', 'Tournez à droite.', 'Turn right.', 'directions'),
      v('traverser', 'to cross', 'tra-vehr-SAY', 'Traversez la rue.', 'Cross the street.', 'directions'),
      v('continuer', 'to continue', 'kon-tee-NWAY', 'Continuez tout droit.', 'Continue straight ahead.', 'directions'),
      v('près de', 'near', 'preh duh', 'La gare est près du musée.', 'The station is near the museum.', 'prepositions'),
      v('derrière', 'behind', 'deh-RYEHR', 'La banque est derrière la poste.', 'The bank is behind the post office.', 'prepositions'),
      v('entre', 'between', 'AHN-truh', 'Le parc est entre deux rues.', 'The park is between two streets.', 'prepositions'),
    ],
    exercises: [
      { id: 'l10-e1', type: 'fill_blank', question: 'La pharmacie est ___ la banque. (behind)', correct_answer: 'derrière', explanation: 'Derrière means behind.' },
      { id: 'l10-e2', type: 'multiple_choice', question: 'Choose the destination phrase: Je vais ___ musée.', options: ['à le', 'au', 'en'], correct_answer: 'au', explanation: 'Au is à + le.' },
      { id: 'l10-e3', type: 'matching', question: 'Match places to categories.', pairs: [{ french: 'gare', english: 'transport' }, { french: 'pharmacie', english: 'health' }, { french: 'banque', english: 'money' }, { french: 'bibliothèque', english: 'books' }], explanation: 'Landmarks help with directions.' },
      { id: 'l10-e4', type: 'fill_blank', question: '___ une pharmacie ici.', correct_answer: 'Il y a', explanation: 'Il y a is the fixed structure for there is/there are.' },
      { id: 'l10-e5', type: 'translation', question: 'EN→FR: Turn right and cross the street.', direction: 'en_to_fr', correct_answer: 'Tournez à droite et traversez la rue.', explanation: 'Use the vous command form for polite directions.' },
      { id: 'l10-e6', type: 'translation', question: 'EN→FR: There is a park near the library.', direction: 'en_to_fr', correct_answer: 'Il y a un parc près de la bibliothèque.', explanation: 'Il y a introduces what exists nearby.' },
      { id: 'l10-e7', type: 'multiple_choice', question: 'Which is correct for a city?', options: ['Je vais à Lyon.', 'Je vais au Lyon.', 'Je vais en Lyon.'], correct_answer: 'Je vais à Lyon.', explanation: 'Cities use à.' },
      { id: 'l10-e8', type: 'speaking_prompt', question: 'Describe where you live using four prepositions.', model_answer: 'Il y a une pharmacie près de ma maison. La banque est devant le parc, et la gare est derrière la mairie.', translation: 'There is a pharmacy near my house. The bank is in front of the park, and the station is behind city hall.', tip: 'Use il y a once, then place nouns with prepositions.' },
    ],
  }),

  makeBase(11, 'Numbers 70-1000 and Dates', 'Les Nombres 70-1000 et les Dates', 'Use larger French numbers, months, seasons, ordinals, and dates.', 3, ['dates', 'calendar', 'numbers'], {
    learning_objectives: [
      'Understand the logic of 70-99',
      'Read and write dates with le plus day and month',
      'Name months and seasons',
      'Use ordinal numbers for dates and rankings',
    ],
    prerequisite_lessons: ['beginner-10'],
    dialogue: {
      title: 'Préparer un voyage',
      context: 'Two colleagues plan trip dates and train tickets.',
      exchanges: [
        { speaker: 'Alice', french: 'Quelle date sommes-nous aujourd’hui?', english: 'What date is it today?', pronunciation: 'kel dat sum noo oh-zhoor-DWEE' },
        { speaker: 'Benoît', french: 'Nous sommes le douze mars.', english: 'It is March twelfth.', pronunciation: 'noo sum luh dooz mars' },
        { speaker: 'Alice', french: 'Le voyage est le premier avril?', english: 'Is the trip on April first?', pronunciation: 'luh vwah-YAZH ay luh pruh-MYAY ah-VREEL' },
        { speaker: 'Benoît', french: 'Oui, et le train est à quatre-vingt-dix euros.', english: 'Yes, and the train is ninety euros.', pronunciation: 'wee ay luh tran ay ah katr-van-DEEZ uh-ROH' },
        { speaker: 'Alice', french: 'C’est cher, mais les vacances sont importantes.', english: 'It’s expensive, but vacations are important.', pronunciation: 'say shehr meh lay vah-KAHNS sohn an-por-TAHNT' },
        { speaker: 'Benoît', french: 'En été, les billets sont souvent chers.', english: 'In summer, tickets are often expensive.', pronunciation: 'ahn nay-TAY lay bee-YEH sohn soo-VAHN shehr' },
        { speaker: 'Alice', french: 'Alors, nous partons en mai.', english: 'So, we leave in May.', pronunciation: 'ah-LOR noo par-TOHN ahn meh' },
        { speaker: 'Benoît', french: 'D’accord. Le rendez-vous est lundi prochain.', english: 'Agreed. The appointment is next Monday.', pronunciation: 'dah-KOR luh rahn-day-VOO ay luhn-DEE pro-SHAN' },
        { speaker: 'Alice', french: 'Je réserve deux billets demain.', english: 'I reserve two tickets tomorrow.', pronunciation: 'zhuh ray-ZERV duh bee-YEH duh-MAN' },
        { speaker: 'Benoît', french: 'Parfait, merci.', english: 'Perfect, thank you.', pronunciation: 'par-FEH mer-SEE' },
      ],
      cultural_notes: [
        'French dates use day-month-year order: 12/03 means March 12, not December 3.',
        'Train prices in France can vary sharply by season, demand, and how early tickets are booked.',
        'Le premier is the only ordinal normally used for calendar dates; other dates use cardinal numbers.',
      ],
    },
    grammar: {
      topic: 'Large Numbers and Dates',
      explanation: 'French numbers from 70 to 99 look strange until you see the arithmetic. Soixante-dix is 60 + 10, quatre-vingts is 4 x 20, and quatre-vingt-dix is 4 x 20 + 10.\n\nDates use a compact pattern: le plus day plus month. Say le douze mars for March twelfth. The first day of a month is special: le premier avril, not le un avril.',
      examples: [
        { french: 'soixante-dix', english: 'seventy', pronunciation: 'swah-sahnt-DEES', highlight: '60 + 10' },
        { french: 'quatre-vingts', english: 'eighty', pronunciation: 'katr-VAN', highlight: '4 x 20' },
        { french: 'le premier avril', english: 'April first', pronunciation: 'luh pruh-MYAY ah-VREEL', highlight: 'premier' },
      ],
      patterns: ['70 = soixante-dix', '80 = quatre-vingts', '90 = quatre-vingt-dix', 'le + date + month', 'en + year', 'en + season for most seasons'],
      tip: 'A useful mnemonic: quatre-vingts is 4 x 20, like counting in groups of twenty.',
    },
    vocabulary: [
      v('soixante-dix', 'seventy', 'swah-sahnt-DEES', 'Le billet est à soixante-dix euros.', 'The ticket is seventy euros.', 'numbers'),
      v('quatre-vingts', 'eighty', 'katr-VAN', 'Il y a quatre-vingts places.', 'There are eighty seats.', 'numbers'),
      v('quatre-vingt-dix', 'ninety', 'katr-van-DEES', 'Le train est à quatre-vingt-dix euros.', 'The train is ninety euros.', 'numbers'),
      v('cent', 'one hundred', 'sahn', 'Cent euros, c’est cher.', 'One hundred euros is expensive.', 'numbers'),
      v('deux cents', 'two hundred', 'duh sahn', 'Deux cents billets sont ici.', 'Two hundred tickets are here.', 'numbers'),
      v('mille', 'one thousand', 'meel', 'Mille ans, c’est long.', 'One thousand years is long.', 'numbers'),
      v('janvier', 'January', 'zhahn-VYAY', 'Mon anniversaire est en janvier.', 'My birthday is in January.', 'months'),
      v('février', 'February', 'fay-vree-YAY', 'Le rendez-vous est en février.', 'The appointment is in February.', 'months'),
      v('mars', 'March', 'mars', 'Nous sommes le douze mars.', 'It is March twelfth.', 'months'),
      v('avril', 'April', 'ah-VREEL', 'Le voyage est le premier avril.', 'The trip is April first.', 'months'),
      v('mai', 'May', 'meh', 'Nous partons en mai.', 'We leave in May.', 'months'),
      v('juin', 'June', 'zhwan', 'La fête est en juin.', 'The party is in June.', 'months'),
      v('juillet', 'July', 'zhwee-YEH', 'Les vacances sont en juillet.', 'Vacation is in July.', 'months'),
      v('août', 'August', 'oot', 'Août est chaud.', 'August is hot.', 'months'),
      v('septembre', 'September', 'sep-TAHMBR', 'La rentrée est en septembre.', 'The return to school is in September.', 'months'),
      v('octobre', 'October', 'ok-TOHBR', 'Octobre est en automne.', 'October is in autumn.', 'months'),
      v('novembre', 'November', 'noh-VAHMBR', 'Novembre est froid.', 'November is cold.', 'months'),
      v('décembre', 'December', 'day-SAHMBR', 'Décembre est important.', 'December is important.', 'months'),
      v('printemps', 'spring', 'pran-TAHN', 'Le printemps est agréable.', 'Spring is pleasant.', 'seasons'),
      v('été', 'summer', 'ay-TAY', 'En été, les billets sont chers.', 'In summer, tickets are expensive.', 'seasons'),
    ],
    exercises: [
      { id: 'l11-e1', type: 'fill_blank', question: '90 = quatre-vingt-___.', correct_answer: 'dix', explanation: '90 is four-twenties-ten.' },
      { id: 'l11-e2', type: 'multiple_choice', question: 'Which number is quatre-vingts?', options: ['70', '80', '90'], correct_answer: '80', explanation: 'Quatre-vingts is 4 x 20.' },
      { id: 'l11-e3', type: 'matching', question: 'Match number logic.', pairs: [{ french: 'soixante-dix', english: '60 + 10' }, { french: 'quatre-vingts', english: '4 x 20' }, { french: 'quatre-vingt-dix', english: '4 x 20 + 10' }, { french: 'cent', english: '100' }], explanation: 'The logic makes 70-99 easier to decode.' },
      { id: 'l11-e4', type: 'fill_blank', question: 'April first = le ___ avril.', correct_answer: 'premier', explanation: 'Use premier for the first day of the month.' },
      { id: 'l11-e5', type: 'translation', question: 'EN→FR: The trip is on May 12.', direction: 'en_to_fr', correct_answer: 'Le voyage est le douze mai.', explanation: 'Dates use le plus number plus month.' },
      { id: 'l11-e6', type: 'matching', question: 'Match seasons.', pairs: [{ french: 'printemps', english: 'spring' }, { french: 'été', english: 'summer' }, { french: 'automne', english: 'autumn' }, { french: 'hiver', english: 'winter' }], explanation: 'Seasons often use en, except au printemps.' },
      { id: 'l11-e7', type: 'multiple_choice', question: 'French date order is usually:', options: ['day-month-year', 'month-day-year', 'year-day-month'], correct_answer: 'day-month-year', explanation: 'French dates put the day first.' },
      { id: 'l11-e8', type: 'speaking_prompt', question: 'Say today’s date and a future travel month.', model_answer: 'Nous sommes le douze mars. Je voyage en mai.', translation: 'It is March twelfth. I travel in May.', tip: 'Use le for the date and en for most months.' },
    ],
  }),

  makeBase(12, 'Essential Irregular Verbs', 'Verbes Irréguliers Essentiels', 'Use faire, venir, pouvoir, vouloir, and futur proche for weekend plans.', 4, ['irregular verbs', 'future proche', 'plans'], {
    learning_objectives: [
      'Conjugate faire, venir, pouvoir, and vouloir',
      'Use pouvoir and vouloir plus infinitive',
      'Form futur proche with aller plus infinitive',
      'Discuss weekend plans with common faire expressions',
    ],
    prerequisite_lessons: ['beginner-11'],
    dialogue: {
      title: 'Plans du week-end',
      context: 'Friends make weekend plans and discuss what they want, can, and are going to do.',
      exchanges: [
        { speaker: 'Manon', french: 'Qu’est-ce que tu veux faire samedi?', english: 'What do you want to do Saturday?', pronunciation: 'kes-kuh too vuh fehr sam-DEE' },
        { speaker: 'Théo', french: 'Je veux faire du sport le matin.', english: 'I want to exercise in the morning.', pronunciation: 'zhuh vuh fehr doo spor luh mah-TAN' },
        { speaker: 'Manon', french: 'Je peux venir avec toi?', english: 'Can I come with you?', pronunciation: 'zhuh puh vuh-NEER ah-VEK twah' },
        { speaker: 'Théo', french: 'Oui, tu peux venir.', english: 'Yes, you can come.', pronunciation: 'wee too puh vuh-NEER' },
        { speaker: 'Manon', french: 'Après, nous allons faire les courses.', english: 'Afterward, we are going to do the shopping.', pronunciation: 'ah-PREH noo zah-LOHN fehr lay koors' },
        { speaker: 'Théo', french: 'Je ne peux pas. Je viens de réserver un billet.', english: 'I can’t. I have just reserved a ticket.', pronunciation: 'zhuh nuh puh pah zhuh vyahn duh ray-zehr-VAY uhn bee-YEH' },
        { speaker: 'Manon', french: 'Tu vas faire un voyage?', english: 'Are you going to take a trip?', pronunciation: 'too vah fehr uhn vwah-YAZH' },
        { speaker: 'Théo', french: 'Oui, je vais venir à Lyon dimanche.', english: 'Yes, I am going to come to Lyon Sunday.', pronunciation: 'wee zhuh veh vuh-NEER ah lee-OHN dee-MAHNSH' },
        { speaker: 'Manon', french: 'Je veux faire la cuisine ce soir.', english: 'I want to cook tonight.', pronunciation: 'zhuh vuh fehr lah kwee-ZEEN suh swahr' },
        { speaker: 'Théo', french: 'Parfait, nous pouvons manger ensemble.', english: 'Perfect, we can eat together.', pronunciation: 'par-FEH noo poo-VOHN mahn-ZHAY ahn-SAHMBL' },
      ],
      cultural_notes: [
        'Faire is used in many everyday expressions where English uses “do,” “make,” or a specific activity verb.',
        'Weekend planning often uses futur proche in speech because it is simple and immediate.',
        'Venir de plus infinitive is introduced here as a fixed “just did” preview; its full tense system comes later.',
      ],
    },
    grammar: {
      topic: 'Faire, Venir, Pouvoir, Vouloir, and Futur Proche',
      explanation: 'These irregular verbs are high-frequency because they let you talk about action, movement, ability, and intention. Faire appears in many everyday expressions; venir means to come; pouvoir means can or be able to; vouloir means want.\n\nPouvoir and vouloir are usually followed by an infinitive: je peux venir, je veux manger. To talk about near future plans, use aller in the present plus an infinitive: je vais réserver, nous allons partir.',
      examples: [
        { french: 'Je veux faire du sport.', english: 'I want to exercise.', pronunciation: 'zhuh vuh fehr doo spor', highlight: 'veux faire' },
        { french: 'Nous pouvons venir.', english: 'We can come.', pronunciation: 'noo poo-VOHN vuh-NEER', highlight: 'pouvons venir' },
        { french: 'Je vais réserver un billet.', english: 'I am going to reserve a ticket.', pronunciation: 'zhuh veh ray-zehr-VAY uhn bee-YEH', highlight: 'vais réserver' },
      ],
      patterns: ['faire: fais, fais, fait, faisons, faites, font', 'venir: viens, viens, vient, venons, venez, viennent', 'pouvoir: peux, peux, peut, pouvons, pouvez, peuvent', 'vouloir: veux, veux, veut, voulons, voulez, veulent', 'futur proche = aller + infinitive'],
      conjugation_tables: [
        { verb: 'faire', rows: [row('je', 'fais', 'feh'), row('tu', 'fais', 'feh'), row('il/elle/on', 'fait', 'feh'), row('nous', 'faisons', 'fuh-ZOHN'), row('vous', 'faites', 'fet'), row('ils/elles', 'font', 'fohn')] },
        { verb: 'venir', rows: [row('je', 'viens', 'vyahn'), row('tu', 'viens', 'vyahn'), row('il/elle/on', 'vient', 'vyahn'), row('nous', 'venons', 'vuh-NOHN'), row('vous', 'venez', 'vuh-NAY'), row('ils/elles', 'viennent', 'vyen')] },
        { verb: 'pouvoir', rows: [row('je', 'peux', 'puh'), row('tu', 'peux', 'puh'), row('il/elle/on', 'peut', 'puh'), row('nous', 'pouvons', 'poo-VOHN'), row('vous', 'pouvez', 'poo-VAY'), row('ils/elles', 'peuvent', 'puhv')] },
        { verb: 'vouloir', rows: [row('je', 'veux', 'vuh'), row('tu', 'veux', 'vuh'), row('il/elle/on', 'veut', 'vuh'), row('nous', 'voulons', 'voo-LOHN'), row('vous', 'voulez', 'voo-LAY'), row('ils/elles', 'veulent', 'vuhl')] },
      ],
      tip: 'Vouloir and pouvoir are boot verbs: je/tu/il and ils change stems, while nous/vous stay closer to the infinitive.',
    },
    vocabulary: [
      v('faire', 'to do / make', 'fehr', 'Je veux faire du sport.', 'I want to exercise.', 'verbs'),
      v('venir', 'to come', 'vuh-NEER', 'Je peux venir.', 'I can come.', 'verbs'),
      v('pouvoir', 'to be able to / can', 'poo-VWAHR', 'Nous pouvons manger.', 'We can eat.', 'verbs'),
      v('vouloir', 'to want', 'voo-LWAHR', 'Je veux faire la cuisine.', 'I want to cook.', 'verbs'),
      v('faire du sport', 'to exercise / play sports', 'fehr doo spor', 'Je fais du sport.', 'I exercise.', 'faire expressions'),
      v('faire la cuisine', 'to cook', 'fehr lah kwee-ZEEN', 'Elle fait la cuisine.', 'She cooks.', 'faire expressions'),
      v('faire les courses', 'to do grocery shopping', 'fehr lay koors', 'Nous faisons les courses.', 'We do the grocery shopping.', 'faire expressions'),
      v('faire un voyage', 'to take a trip', 'fehr uhn vwah-YAZH', 'Tu vas faire un voyage.', 'You are going to take a trip.', 'faire expressions'),
      v('faire une promenade', 'to take a walk', 'fehr oon prohm-NAD', 'Je veux faire une promenade.', 'I want to take a walk.', 'faire expressions'),
      v('faire attention', 'to pay attention', 'fehr ah-tahn-SYOHN', 'Vous faites attention.', 'You pay attention.', 'faire expressions'),
      v('venir de réserver', 'to have just reserved', 'vuh-NEER duh ray-zehr-VAY', 'Je viens de réserver un billet.', 'I have just reserved a ticket.', 'fixed phrase'),
      v('pouvoir manger', 'to be able to eat', 'poo-VWAHR mahn-ZHAY', 'Nous pouvons manger.', 'We can eat.', 'modal phrase'),
      v('vouloir étudier', 'to want to study', 'voo-LWAHR ay-too-DYAY', 'Je veux étudier.', 'I want to study.', 'modal phrase'),
      v('pouvoir partir', 'to be able to leave', 'poo-VWAHR par-TEER', 'Tu peux partir.', 'You can leave.', 'modal phrase'),
      v('vouloir regarder', 'to want to watch', 'voo-LWAHR ruh-gar-DAY', 'Elle veut regarder un film.', 'She wants to watch a film.', 'modal phrase'),
      v('samedi', 'Saturday', 'sam-DEE', 'Samedi est libre.', 'Saturday is free.', 'time'),
      v('dimanche', 'Sunday', 'dee-MAHNSH', 'Je vais venir dimanche.', 'I am going to come Sunday.', 'time'),
      v('week-end', 'weekend', 'week-END', 'Le week-end est important.', 'The weekend is important.', 'time'),
    ],
    exercises: [
      { id: 'l12-e1', type: 'conjugation', question: 'Conjugate faire.', verb: 'faire', correct_answer: [row('je', 'fais', 'feh'), row('tu', 'fais', 'feh'), row('il/elle/on', 'fait', 'feh'), row('nous', 'faisons', 'fuh-ZOHN'), row('vous', 'faites', 'fet'), row('ils/elles', 'font', 'fohn')], explanation: 'Faire has irregular written and spoken forms.' },
      { id: 'l12-e2', type: 'conjugation', question: 'Conjugate venir.', verb: 'venir', correct_answer: [row('je', 'viens', 'vyahn'), row('tu', 'viens', 'vyahn'), row('il/elle/on', 'vient', 'vyahn'), row('nous', 'venons', 'vuh-NOHN'), row('vous', 'venez', 'vuh-NAY'), row('ils/elles', 'viennent', 'vyen')], explanation: 'Venir changes stem in the singular and ils/elles forms.' },
      { id: 'l12-e3', type: 'multiple_choice', question: 'Choose the correct form: nous ___ venir.', options: ['peut', 'pouvons', 'peuvent'], correct_answer: 'pouvons', explanation: 'Nous takes pouvons.' },
      { id: 'l12-e4', type: 'transformation', question: 'Change present plans to futur proche.', instruction: 'affirmative_to_negative', items: [{ original: 'Je réserve un billet.', transformed: 'Je vais réserver un billet.', translation: 'I am going to reserve a ticket.' }, { original: 'Nous faisons les courses.', transformed: 'Nous allons faire les courses.', translation: 'We are going to do the shopping.' }], explanation: 'Use aller plus infinitive.' },
      { id: 'l12-e5', type: 'fill_blank', question: 'Je ___ faire du sport.', correct_answer: 'veux', explanation: 'Je takes veux.' },
      { id: 'l12-e6', type: 'matching', question: 'Match faire expressions.', pairs: [{ french: 'faire du sport', english: 'to exercise' }, { french: 'faire la cuisine', english: 'to cook' }, { french: 'faire les courses', english: 'to do grocery shopping' }, { french: 'faire un voyage', english: 'to take a trip' }], explanation: 'Faire expressions are learned as chunks.' },
      { id: 'l12-e7', type: 'translation', question: 'EN→FR: We can eat together.', direction: 'en_to_fr', correct_answer: 'Nous pouvons manger ensemble.', explanation: 'Pouvoir is followed by an infinitive.' },
      { id: 'l12-e8', type: 'speaking_prompt', question: 'Describe your weekend with futur proche and two irregular verbs.', model_answer: 'Samedi, je vais faire du sport. Dimanche, je veux venir à Lyon et je peux manger avec mes amis.', translation: 'Saturday, I am going to exercise. Sunday, I want to come to Lyon and I can eat with my friends.', tip: 'Keep modal verbs conjugated and the next verb in the infinitive.' },
    ],
  }),
]

export const getBeginnerLessons = () => beginnerLessons
export const getBeginnerLesson = (id: string) => beginnerLessons.find((lesson) => lesson.id === id)
